import { OperationsWorkspace } from "@/components/operations-workspace";
import { PlaceholderPage } from "@/components/placeholder-page";
import { MembersWorkspace } from "@/components/members-workspace";
import { AuditWorkspace } from "@/components/audit-workspace";
import { GoalsWorkspace } from "@/components/goals-workspace";
import { ProjectHubWorkspace } from "@/components/project-hub-workspace";
import { MeetingWorkspace } from "@/components/meeting-workspace";
import { ContentAutomationWorkspace } from "@/components/content-automation-workspace";
import { PublishingCalendarWorkspace } from "@/components/publishing-calendar-workspace";
import { SkillsWorkspace } from "@/components/skills-workspace";
import { GrowthDashboard } from "@/components/growth-dashboard";
import { ReportsWorkspace } from "@/components/reports-workspace";
import { MonitoringWorkspace } from "@/components/monitoring-workspace";
import { TasksWorkspace } from "@/components/tasks-workspace";
import { AcquisitionFunnelWorkspace, CommerceAdminLinks, RevenueWorkspace, WeeklyKpiWorkspace } from "@/components/performance-workspaces";
import { NAV_STAGES } from "@/lib/navigation";
import { WORKSPACE_CONFIGS } from "@/lib/workspace-config";

export default async function GenericPage({ params }: { params: Promise<{ stage: string; page: string }> }) {
  const resolved = await params;
  const href = `/${resolved.stage}/${resolved.page}`;
  const stage = NAV_STAGES.find((item) => item.pages.some((page) => page.href === href));
  const page = stage?.pages.find((item) => item.href === href);
  if (href === "/organization/members") return <MembersWorkspace />;
  if (href === "/settings/audit") return <AuditWorkspace />;
  if (href === "/home/goals") return <GoalsWorkspace />;
  if (href === "/home/reports") return <ReportsWorkspace />;
  if (href === "/organization/projects") return <ProjectHubWorkspace />;
  if (href === "/organization/meetings") return <MeetingWorkspace />;
  if (href === "/organization/tasks") return <TasksWorkspace />;
  if (href === "/content/automation") return <ContentAutomationWorkspace />;
  if (href === "/content/review") return <ContentAutomationWorkspace initialView="review" />;
  if (href === "/content/calendar") return <PublishingCalendarWorkspace />;
  if (href === "/knowledge/skills") return <SkillsWorkspace />;
  if (href === "/performance/overview") return <GrowthDashboard />;
  if (href === "/performance/revenue") return <RevenueWorkspace />;
  if (href === "/performance/funnels") return <AcquisitionFunnelWorkspace />;
  if (href === "/performance/weekly-kpi") return <WeeklyKpiWorkspace />;
  if (href === "/performance/crm") return <CommerceAdminLinks title="CRM 관리자" />;
  if (href === "/performance/customers") return <CommerceAdminLinks title="고객·주문 관리자" />;
  if (href === "/settings/monitoring") return <MonitoringWorkspace />;
  const config = WORKSPACE_CONFIGS[href];
  if (config) return <OperationsWorkspace config={config} />;
  return <PlaceholderPage title={page?.label ?? "기능 준비"} stage={stage?.label ?? "OS"} />;
}
