import { OperationsWorkspace } from "@/components/operations-workspace";
import { PlaceholderPage } from "@/components/placeholder-page";
import { MembersWorkspace } from "@/components/members-workspace";
import { AuditWorkspace } from "@/components/audit-workspace";
import { GoalsWorkspace } from "@/components/goals-workspace";
import { redirect } from "next/navigation";
import { MeetingWorkspace } from "@/components/meeting-workspace";
import { ContentAutomationWorkspace } from "@/components/content-automation-workspace";
import { PublishingCalendarWorkspace } from "@/components/publishing-calendar-workspace";
import { SkillsWorkspace } from "@/components/skills-workspace";
import { GrowthDashboard } from "@/components/growth-dashboard";
import { ReportsWorkspace } from "@/components/reports-workspace";
import { MonitoringWorkspace } from "@/components/monitoring-workspace";
import { TasksWorkspace } from "@/components/tasks-workspace";
import { AiOperationsWorkspace, LeaveWorkspace, WeeklyScheduleWorkspace } from "@/components/organization-v3-workspaces";
import { FinanceWorkspace } from "@/components/finance-workspace";
import { AcquisitionFunnelWorkspace, CommerceAdminLinks, RevenueWorkspace, WeeklyKpiWorkspace } from "@/components/performance-workspaces";
import { AdPerformanceWorkspace } from "@/components/ad-performance-workspace";
import { ContentPackageWorkspace, ContentShortsWorkspace, YoutubeKitWorkspace } from "@/components/content-studio-workspaces";
import { ContentPerformanceWorkspace, ContentScriptsWorkspace, ContentTopicsWorkspace } from "@/components/content-pipeline-workspaces";
import { SettingsWorkspace } from "@/components/settings-workspaces";
import { NAV_STAGES } from "@/lib/navigation";
import { WORKSPACE_CONFIGS } from "@/lib/workspace-config";

export default async function GenericPage({ params }: { params: Promise<{ stage: string; page: string }> }) {
  const resolved = await params;
  const href = `/${resolved.stage}/${resolved.page}`;
  const stage = NAV_STAGES.find((item) => item.pages.some((page) => page.href === href));
  const page = stage?.pages.find((item) => item.href === href);
  if (href === "/organization/members") return <MembersWorkspace />;
  if (href === "/settings/audit") return <AuditWorkspace />;
  if (href === "/home/goals") return <GoalsWorkspace />;
  if (href === "/home/reports") return <ReportsWorkspace />;
  if (href === "/organization/projects") redirect("/organization/tasks");
  if (href === "/organization/meetings") return <MeetingWorkspace />;
  if (href === "/organization/tasks") return <TasksWorkspace />;
  if (href === "/organization/schedule") return <WeeklyScheduleWorkspace />;
  if (href === "/organization/leave") return <LeaveWorkspace />;
  if (href === "/organization/agents") return <AiOperationsWorkspace />;
  if (href === "/organization/finance") return <FinanceWorkspace />;
  if (href === "/content/topics") return <ContentTopicsWorkspace />;
  if (href === "/content/scripts") return <ContentScriptsWorkspace />;
  if (href === "/content/automation") return <ContentAutomationWorkspace />;
  if (href === "/content/review") return <ContentAutomationWorkspace initialView="review" />;
  if (href === "/content/packages") return <ContentPackageWorkspace />;
  if (href === "/content/shorts") return <ContentShortsWorkspace />;
  if (href === "/content/publishing") return <ContentAutomationWorkspace initialView="review" />;
  if (href === "/content/youtube") return <YoutubeKitWorkspace />;
  if (href === "/content/calendar") return <PublishingCalendarWorkspace />;
  if (href === "/content/performance") return <ContentPerformanceWorkspace />;
  if (href === "/knowledge/skills") return <SkillsWorkspace />;
  if (href === "/performance/overview") return <GrowthDashboard />;
  if (href === "/performance/revenue") return <RevenueWorkspace />;
  if (href === "/performance/funnels") return <AcquisitionFunnelWorkspace />;
  if (href === "/performance/ads") return <AdPerformanceWorkspace />;
  if (href === "/performance/weekly-kpi") return <WeeklyKpiWorkspace />;
  if (href === "/performance/customers") return <CommerceAdminLinks title="자사몰 어드민" />;
  if (href === "/settings/monitoring") return <MonitoringWorkspace />;
  if (href === "/settings/connections") return <SettingsWorkspace page="connections" />;
  if (href === "/settings/access") return <SettingsWorkspace page="access" />;
  if (href === "/settings/company") return <SettingsWorkspace page="company" />;
  if (href === "/settings/channels") return <SettingsWorkspace page="channels" />;
  const config = WORKSPACE_CONFIGS[href];
  if (config) return <OperationsWorkspace config={config} />;
  return <PlaceholderPage title={page?.label ?? "기능 준비"} stage={stage?.label ?? "OS"} />;
}
