"use client";
import Link from "next/link";
import { useRouter,useSearchParams } from "next/navigation";
import { useEffect,useState } from "react";
import {TagPicker} from "./tag-picker";
import { Header,Card,Empty,Modal } from "./ui";
import { useKnowledge } from "./provider";
import { kstDay,kstTime,type Proposal } from "@/lib/knowledge/model";
import { ProposalComments } from "./proposal-comments";
import { KnowledgeDocumentPage } from "./editor";
import { KnowledgeRichEditor } from "@/components/knowledge-rich-editor";
import { diffMarkdownLines } from "@/lib/line-diff";
import { mergeMarkdown,mergeValue,joinMergeParts } from "@/lib/knowledge/merge";
import { canDecideProposal } from "@/lib/knowledge/access";
import type { KnowledgeDocument,DocumentVersion } from "@/lib/types";
import { apiRequest } from "@/lib/api-client";

export function KnowledgeCanon(){
  const {state}=useKnowledge(),params=useSearchParams(),router=useRouter();
  const [q,setQ]=useState(""),[page,setPage]=useState(0);const folder=params.get("folder")??"",filter=params.get("filter")??"all";
  const all=state.documents.filter(d=>d.status==="canonical");
  const proposals=new Set(state.proposals.filter(p=>p.status==="open").map(p=>p.document_id));
  const overdue=(d:KnowledgeDocument)=>Boolean(d.review_due_on&&d.review_due_on<kstDay());
  const rows=all.filter(d=>(!folder||d.folder===folder||d.folder.startsWith(folder+"/"))&&d.title.toLowerCase().includes(q.toLowerCase())&&(filter==="all"||filter==="overdue"&&overdue(d)||filter==="nosteward"&&!d.steward_id||filter==="proposal"&&proposals.has(d.id))).sort((a,b)=>b.updated_at.localeCompare(a.updated_at));
  function query(patch:Record<string,string>){const next=new URLSearchParams(params);Object.entries(patch).forEach(([k,v])=>v?next.set(k,v):next.delete(k));setPage(0);router.replace(`/knowledge/canon?${next}`);}
  return <><Header title="회사 정본" description="승인된 업무 기준입니다. 직접 덮어쓰지 않고 변경 제안을 통해 새 버전으로 갱신합니다."/><div className="kw-metrics">{[["all","전체 정본",all.length],["overdue","검토 기한 지남",all.filter(overdue).length],["nosteward","담당자 미지정",all.filter(d=>!d.steward_id).length],["proposal","변경 제안 대기",proposals.size]].map(([key,label,count])=><button className="kw-card" key={key} aria-pressed={filter===key} onClick={()=>query({filter:String(key)})}><span>{label}<strong>{count}</strong></span></button>)}</div><div className="kw-db"><aside className="kw-card kw-categories"><h3>정본 폴더</h3><button aria-pressed={!folder} onClick={()=>query({folder:""})}>전체 폴더</button>{[...new Set(all.map(d=>d.folder))].sort().map(f=><button key={f} aria-pressed={folder===f} onClick={()=>query({folder:f})}>{f||"분류 없음"}<small>{all.filter(d=>d.folder===f).length}</small></button>)}</aside><div><div className="kw-toolbar"><input aria-label="정본 검색" placeholder="정본 제목 검색" value={q} onChange={e=>{setQ(e.target.value);setPage(0);}}/><small>{rows.length}개</small></div><div className="kw-table-wrap"><table className="kw-table"><thead><tr><th>정본</th><th>담당자</th><th>검토일</th><th>버전</th><th>수정</th></tr></thead><tbody>{rows.slice(page*50,(page+1)*50).map(d=><tr key={d.id}><td><Link href={`/knowledge/canon/${d.id}`}>{d.title}</Link>{proposals.has(d.id)&&<span className="kw-badge">변경 제안</span>}</td><td>{state.people.find(p=>p.id===d.steward_id)?.display_name??"미지정"}</td><td className={overdue(d)?"kw-danger":""}>{d.review_due_on??"미지정"}</td><td>v{d.current_version}</td><td>{kstTime(d.updated_at)}</td></tr>)}</tbody></table>{!rows.length&&<Empty>조건에 맞는 정본이 없습니다</Empty>}</div><div className="kw-toolbar"><button disabled={!page} onClick={()=>setPage(page-1)}>이전</button><small>{page+1} / {Math.max(1,Math.ceil(rows.length/50))}</small><button disabled={(page+1)*50>=rows.length} onClick={()=>setPage(page+1)}>다음</button></div></div></div></>;
}
export function KnowledgeCanonDocument({id}:{id:string}){return <KnowledgeDocumentPage id={id}/>;}
export function KnowledgeProposalPage({id}:{id:string}){
  const {loadDocument,loading,demo,token,state}=useKnowledge(),params=useSearchParams();
  const versionNumber=Number(params.get("version"))||0;
  const [historical,setHistorical]=useState<DocumentVersion|null>(null),[doc,setDoc]=useState<KnowledgeDocument|null>(null),[error,setError]=useState("");
  useEffect(()=>{if(loading)return;let live=true;setDoc(null);setError("");void loadDocument(id).then(async d=>{
    let selected:DocumentVersion|null=null;
    if(versionNumber){const versions=demo?state.versions[id]??[]:(await apiRequest<{versions:DocumentVersion[]}>(`/api/v1/documents/${id}/versions`,{token})).versions;selected=versions.find(v=>v.version_no===versionNumber)??null;if(!selected)throw Error("선택한 과거 버전을 찾을 수 없습니다.");}
    if(live){setHistorical(selected);setDoc(d);}
  }).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[id,loadDocument,loading,versionNumber,demo,token,state.versions]);
  return error?<Empty>{error}</Empty>:!doc?<Empty>정본을 불러오는 중입니다</Empty>:doc.status!=="canonical"?<Empty>회사 정본만 변경 제안을 작성합니다</Empty>:<ProposalEditor key={doc.id+":"+versionNumber} doc={doc} historical={historical}/>;
}
function ProposalEditor({doc,historical}:{doc:KnowledgeDocument;historical:DocumentVersion|null}){
  const {state,actor,command,notify,token}=useKnowledge(),router=useRouter(),params=useSearchParams();
  const prior=state.proposals.find(p=>p.id===params.get("proposal")&&p.author_id===actor.ownerId&&p.status==="returned"&&p.return_kind==="revise");
  const draft=state.drafts.find(d=>d.document_id===doc.id);
  const [title,setTitle]=useState(historical?.title??prior?.title??draft?.title??doc.title),[content,setContent]=useState(historical?.content_md??prior?.content_md??draft?.content_md??doc.content_md),[folder,setFolder]=useState(prior?.folder??doc.folder),[tags,setTags]=useState((prior?.tags??doc.tags).join(", "));
  const [reason,setReason]=useState(historical?`v${historical.version_no} 내용으로 복원 제안`:prior?.author_note??""),[approver,setApprover]=useState(prior?.requested_approver_id??""),[due,setDue]=useState(prior?.review_due_on??doc.review_due_on??""),[ai,setAi]=useState(prior?.ai_assist??"");
  const [busy,setBusy]=useState(false),[error,setError]=useState(""),[saved,setSaved]=useState("");
  const baseVersion=historical?doc.current_version:prior?.base_version??draft?.base_version??doc.current_version;
  useEffect(()=>{if(title===doc.title&&content===doc.content_md)return;const timer=setTimeout(()=>void command({action:"document.draft",id:doc.id,title,content,expectedVersion:baseVersion}).then(()=>setSaved("제안 본문 임시 저장됨")).catch(e=>setError(e.message)),1500);return()=>clearTimeout(timer);},[title,content,doc.id,doc.title,doc.content_md,baseVersion,command]);
  async function submit(){setBusy(true);try{const result=await command({action:"proposal.create",id:doc.id,proposalId:prior?.id,expectedVersion:baseVersion,title,content,folder,tags:tags.split(",").map(t=>t.trim()).filter(Boolean),reason,approverId:approver,reviewDueOn:due,aiAssist:ai});notify("변경 제안을 보냈습니다. 정본은 승인 전까지 그대로 유지됩니다.");router.push("/knowledge/review?tab=sent"+(result.id?"&id="+encodeURIComponent(result.id):""));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <><Header title="정본 변경 제안" description={`원본 v${doc.current_version} · 제안 기준 v${baseVersion} · ${saved||"본문만 임시 저장됩니다"}`}><Link href={`/knowledge/canon/${doc.id}`}>정본으로 돌아가기</Link><button className="kw-primary" disabled={busy||!reason.trim()||!approver} onClick={()=>void submit()}>{prior?"수정하여 다시 제출":"변경 제안 보내기"}</button></Header>{baseVersion!==doc.current_version&&<p className="kw-conflict">기준 버전이 오래되었습니다. 제출 후 최신 정본과 충돌을 해결해야 승인할 수 있습니다.</p>}<div className="kw-meeting-layout"><Card title="제안 내용"><input aria-label="제안 제목" value={title} onChange={e=>setTitle(e.target.value)}/><KnowledgeRichEditor markdown={content} accessToken={token} onChange={setContent} onError={setError}/></Card><aside className="kw-card kw-stack"><label>변경 이유 (필수 · 200자)<textarea required maxLength={200} value={reason} onChange={e=>setReason(e.target.value)}/></label><label>승인자<select value={approver} onChange={e=>setApprover(e.target.value)}><option value="">승인자 선택</option>{state.people.filter(p=>p.can_approve&&p.member_kind==="staff"&&![actor.ownerId,doc.owner_id].includes(p.id)).map(p=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select></label><label>정본 폴더<input value={folder} onChange={e=>setFolder(e.target.value)}/></label><TagPicker value={tags.split(",").map(t=>t.trim()).filter(Boolean)} onChange={values=>setTags(values.join(", "))}/><label>검토일<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><label>AI 도움을 받은 부분 (선택)<textarea value={ai} onChange={e=>setAi(e.target.value)}/></label>{error&&<p className="kw-error" role="alert">{error}</p>}<small>작성자·문서 소유자는 이 제안을 승인할 수 없습니다.</small></aside></div></>;
}
export function KnowledgeReview(){
  const {state,actor}=useKnowledge(),params=useSearchParams();
  const tab=params.get("tab")??"todo",selected=params.get("id")??params.get("proposal")??state.proposals.find(p=>p.document_id===params.get("document")&&p.status==="open")?.id??state.candidates.find(c=>c.document_id===params.get("document")&&c.status==="open")?.id;
  const proposals=state.proposals.filter(p=>tab==="sent"?p.author_id===actor.ownerId:tab==="done"?p.status!=="open"&&(p.author_id===actor.ownerId||p.reviewer_id===actor.ownerId):p.status==="open"&&p.author_id!==actor.ownerId&&(p.requested_approver_id===actor.ownerId||!p.requested_approver_id&&actor.role==="admin"));
  const candidates=state.candidates.filter(c=>tab==="sent"?c.submitted_by===actor.ownerId:tab==="done"?c.status!=="open":c.status==="open"&&c.submitted_by!==actor.ownerId&&c.requested_approver_id===actor.ownerId);
  const proposal=state.proposals.find(p=>p.id===(selected??proposals[0]?.id));
  const candidate=state.candidates.find(c=>c.id===(selected??(!proposal?candidates[0]?.id:undefined)));
  return <><Header title="검토함" description="정본 변경 제안·정본 후보·회의 검수를 확인합니다."/><nav className="kw-tabs">{[["todo","내가 검토할 것"],["sent","내가 보낸 것"],["done","완료"]].map(([value,label])=><Link key={value} aria-current={tab===value?"page":undefined} href={`/knowledge/review?tab=${value}`}>{label}</Link>)}</nav><div className="kw-review-layout"><aside className="kw-card kw-review-list">{proposals.map(p=><Link key={p.id} aria-current={proposal?.id===p.id&&!candidate?"page":undefined} href={`/knowledge/review?tab=${tab}&id=${p.id}`}><strong>{p.title}</strong><small>변경 제안 · {p.status==="open"?"검토 대기":p.status==="approved"?"승인":p.status==="withdrawn"?"철회":p.return_kind==="reject"?"반려":"보완 요청"}</small></Link>)}{candidates.map(c=><Link key={c.id} href={`/knowledge/review?tab=${tab}&id=${c.id}`}><strong>{state.documents.find(d=>d.id===c.document_id)?.title??"문서"}</strong><small>정본 후보 · {c.status}</small></Link>)}{tab==="todo"&&state.meetings.filter(m=>m.status==="review"&&(m.owner_id===actor.ownerId||actor.role==="admin")).map(m=><Link key={m.id} href={`/knowledge/meetings/${m.id}`}><strong>{m.title}</strong><small>회의 검수</small></Link>)}{!proposals.length&&!candidates.length&&<Empty>검토 항목이 없습니다</Empty>}</aside><main>{candidate?<CandidateReview key={candidate.id} id={candidate.id}/>:proposal?<ProposalReview key={proposal.id} proposal={proposal}/>:<Empty>왼쪽에서 검토할 항목을 선택하세요</Empty>}</main></div></>;
}
function CandidateReview({id}:{id:string}){
  const {state,actor,command,notify}=useKnowledge();const c=state.candidates.find(c=>c.id===id)!,doc=state.documents.find(d=>d.id===c.document_id);
  const [reason,setReason]=useState(""),[busy,setBusy]=useState(false);if(!doc)return <Empty>이 문서를 볼 권한이 없습니다</Empty>;
  const allowed=canDecideProposal(actor,{author_id:c.submitted_by,requested_approver_id:c.requested_approver_id},doc,reason);
  async function decide(decision:string){setBusy(true);try{await command({action:"candidate.decide",id,expectedVersion:doc!.current_version,decision,reason});notify("후보 검토 결과를 저장했습니다");}catch(e){notify((e as Error).message);}finally{setBusy(false);}}
  return <Card title={doc.title}><p>정본 후보 · 현재 v{doc.current_version}을 유지하여 정본으로 올립니다.</p><p>폴더 {c.target_folder||"미분류"} · 검토일 {c.review_due_on}</p><Link href={`/knowledge/doc/${doc.id}`}>문서 내용 확인</Link><label>검토 메모 / 대리 처리 사유<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="kw-actions">{c.status==="open"&&<><button disabled={!allowed||busy||!reason.trim()} onClick={()=>void decide("returned")}>보완 요청</button><button className="kw-primary" disabled={!allowed||busy} onClick={()=>void decide("approved")}>정본 승인</button>{c.submitted_by===actor.ownerId&&<button disabled={busy} onClick={()=>void command({action:"candidate.withdraw",id}).catch(e=>notify(e.message))}>후보 철회</button>}</>}</div>{!allowed&&<small>작성자·문서 소유자는 승인할 수 없습니다. 지정 승인자 또는 사유를 남긴 관리자가 처리합니다.</small>}</Card>;
}
function ProposalReview({proposal:p}:{proposal:Proposal}){
  const {state,actor,command,loadDocument,notify,token,demo}=useKnowledge();
  const [commentLine,setCommentLine]=useState<number|null>(null);
  const [doc,setDoc]=useState<KnowledgeDocument|null>(null),[base,setBase]=useState<DocumentVersion|null>(null),[reason,setReason]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[all,setAll]=useState(false),[merge,setMerge]=useState(false);
  useEffect(()=>{let live=true;void loadDocument(p.document_id).then(async d=>{if(!live)return;setDoc(d);const versions=demo?state.versions[d.id]??[]:(await apiRequest<{versions:DocumentVersion[]}>(`/api/v1/documents/${d.id}/versions`,{token})).versions;if(live)setBase(versions.find(v=>v.version_no===p.base_version)??(p.base_version===d.current_version?{...d,version_no:d.current_version,author_id:d.owner_id,author_name:"",reason:""}:null));}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[p.document_id,p.base_version,p.status,loadDocument,token,demo,state.versions]);
  if(!doc)return <Empty>{error||"검토 내용을 불러오는 중입니다"}</Empty>;
  const allowed=canDecideProposal(actor,p,doc,reason),outdated=p.base_version!==doc.current_version;
  const diff=base?diffMarkdownLines(base.content_md,p.content_md):[];
  async function decide(decision:string){setBusy(true);setError("");try{await command({action:"proposal.decide",id:p.id,decision,reason});notify("검토 결과를 저장했습니다.");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <Card title={p.title}><p>{p.author_note||"변경 이유 미기록"} · 기준 v{p.base_version} → 현재 v{doc.current_version}</p>{p.ai_assist&&<p><small>AI 도움: {p.ai_assist}</small></p>}{outdated&&p.status==="open"&&<div className="kw-conflict">정본이 변경되어 승인할 수 없습니다. {base&&(p.author_id===actor.ownerId||allowed)&&<button onClick={()=>setMerge(true)}>최신 정본과 충돌 해결</button>}</div>}{!base?<p className="kw-error">기준 버전을 확인하지 못했습니다. 비교 확인 전 승인을 진행할 수 없습니다.</p>:<><div className="kw-actions"><button onClick={()=>setAll(!all)}>{all?"변경 부분만":"전체 내용"}</button><Link href={`/knowledge/canon/${doc.id}`}>현재 정본</Link></div><div className="kw-diff" aria-label="변경 비교">{diff.map((line,i)=>(all||line.kind!=="same"||diff[i-1]?.kind!=="same"||diff[i+1]?.kind!=="same")&&<div className={`kw-diff-${line.kind}`} key={i}><small>{line.oldLine??" "} {line.newLine??" "}</small><span>{line.kind==="added"?"+":line.kind==="removed"?"−":" "}</span><code>{line.text||" "}</code>{line.newLine!==null&&p.status==="open"&&<button aria-label={`${line.newLine}행 댓글`} onClick={()=>setCommentLine(line.newLine)}>댓글</button>}</div>)}</div>{[["제목",base.title,p.title],["폴더",doc.folder,p.folder],["태그",doc.tags.join(", "),p.tags.join(", ")],["검토일",doc.review_due_on??"",p.review_due_on??""]].filter(([,a,b])=>a!==b).map(([label,a,b])=><p key={label}><strong>{label}</strong> <del>{a||"없음"}</del> → {b||"없음"}</p>)}</>}<ProposalComments proposal={p} line={commentLine}/><label>검토 메모 / 대리 처리 사유<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={2000}/></label>{error&&<p className="kw-error" role="alert">{error}</p>}<div className="kw-actions">{p.status==="open"&&<><button disabled={busy||!allowed||!reason.trim()} onClick={()=>void decide("rejected")}>반려</button><button disabled={busy||!allowed||!reason.trim()} onClick={()=>void decide("returned")}>보완 요청</button><button className="kw-primary" disabled={busy||!allowed||outdated||!base} onClick={()=>void decide("approved")}>변경 승인</button>{p.author_id===actor.ownerId&&<button disabled={busy} onClick={()=>void decide("withdrawn")}>철회</button>}</>}{p.author_id===actor.ownerId&&p.status==="returned"&&p.return_kind==="revise"&&<Link href={`/knowledge/canon/${doc.id}/propose?proposal=${p.id}`}>보완하여 다시 제출</Link>}</div>{!allowed&&<small>작성자·문서 소유자는 자신의 제안을 승인할 수 없습니다.</small>}{p.note&&<p>검토 의견: {p.note}</p>}{merge&&base&&<MergeDialog proposal={p} current={doc} base={base} close={()=>setMerge(false)}/>}</Card>;
}
function MergeDialog({proposal:p,current:d,base,close}:{proposal:Proposal;current:KnowledgeDocument;base:DocumentVersion;close:()=>void}){
  const {command}=useKnowledge(),[parts,setParts]=useState(()=>mergeMarkdown(base.content_md,d.content_md,p.content_md));
  const [resolved,setResolved]=useState<Set<string>>(new Set()),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const titleMerge=mergeValue(base.title,d.title,p.title);const [title,setTitle]=useState(titleMerge.value),[titleResolved,setTitleResolved]=useState(!titleMerge.conflict);
  const [folder,setFolder]=useState(p.folder),[tags,setTags]=useState(p.tags.join(", ")),[due,setDue]=useState(p.review_due_on??""),[metaConfirmed,setMetaConfirmed]=useState(false);
  async function save(){setBusy(true);try{await command({action:"proposal.rebase",id:p.id,expectedVersion:d.current_version,title,content:joinMergeParts(parts),folder,tags:tags.split(",").map(t=>t.trim()).filter(Boolean),reviewDueOn:due});close();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <Modal title="최신 정본과 충돌 해결" onClose={close} busy={busy}><div className="kw-modal-body"><p>기준 v{p.base_version} · 현재 v{d.current_version}. 자동 병합 결과를 확인하고 모든 충돌을 선택하세요.</p>{parts.map((part,i)=><section className="kw-card kw-stack" key={part.id}>{part.conflict?<><h3>본문 충돌 {i+1}</h3><details><summary>기준 내용</summary><pre>{part.base}</pre></details><div className="kw-home-grid"><div><strong>현재 정본</strong><pre>{part.current}</pre><button onClick={()=>{setParts(parts.map(x=>x.id===part.id?{...x,value:part.current,valueLines:part.currentLines}:x));setResolved(new Set([...resolved,part.id]));}}>현재 내용 선택</button></div><div><strong>내 제안</strong><pre>{part.proposed}</pre><button onClick={()=>{setParts(parts.map(x=>x.id===part.id?{...x,value:part.proposed,valueLines:part.proposedLines}:x));setResolved(new Set([...resolved,part.id]));}}>제안 내용 선택</button></div></div><label>직접 편집<textarea value={part.value} onChange={e=>{setParts(parts.map(x=>x.id===part.id?{...x,value:e.target.value,valueLines:e.target.value.split("\n").length}:x));setResolved(new Set([...resolved,part.id]));}}/></label><small>{resolved.has(part.id)?"해결됨":"선택 필요"}</small></>:<pre>{part.value}</pre>}</section>)}<label>제목 {titleMerge.conflict?"· 충돌":""}<input value={title} onChange={e=>{setTitle(e.target.value);setTitleResolved(true);}}/></label>{titleMerge.conflict&&<button onClick={()=>{setTitle(d.title);setTitleResolved(true);}}>현재 제목 사용: {d.title}</button>}<p>속성은 현재 정본과 제안을 함께 확인해 확정하세요. 과거 버전에 속성 스냅샷이 없는 항목은 자동으로 판단하지 않습니다.</p><small>현재 폴더: {d.folder} · 현재 태그: {d.tags.join(", ")} · 현재 검토일: {d.review_due_on||"없음"}</small><label>확정 폴더<input value={folder} onChange={e=>setFolder(e.target.value)}/></label><label>확정 태그<input value={tags} onChange={e=>setTags(e.target.value)}/></label><label>확정 검토일<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><label className="kw-actions"><input type="checkbox" checked={metaConfirmed} onChange={e=>setMetaConfirmed(e.target.checked)}/>속성 병합 결과를 확인했습니다</label>{error&&<p className="kw-error">{error}</p>}<footer><button disabled={busy} onClick={close}>취소</button><button className="kw-primary" disabled={busy||!titleResolved||!metaConfirmed||parts.some(p=>p.conflict&&!resolved.has(p.id))} onClick={()=>void save()}>최신 버전 기준으로 저장</button></footer></div></Modal>;
}
