"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState, type ReactNode } from "react";
import { X, Plus, LockKeyhole, Users, ShieldCheck, CalendarDays, Pin, ArrowUpRight, FileText } from "lucide-react";
import { KnowledgeModal } from "@/components/knowledge-modal";
import { documentHref, documentSpace, kstTime, SPACE_LABELS, type Space, type Template } from "@/lib/knowledge/model";
import type { KnowledgeDocument } from "@/lib/types";
import { useKnowledge } from "./provider";

export function SpaceBadge({ space }: { space: Space }) { const Icon = space === "mine" ? LockKeyhole : space === "canon" ? ShieldCheck : space === "meet" ? CalendarDays : Users; return <span className={`kw-badge kw-${space}`}><Icon size={12}/>{SPACE_LABELS[space]}</span>; }
export function Header({ title, description, children }: { title: string; description?: string; children?: ReactNode }) { return <header className="kw-header"><div><h1>{title}</h1>{description && <p>{description}</p>}</div><div className="kw-actions">{children}</div></header>; }
export function Empty({ children }: { children: ReactNode }) { return <div className="kw-empty"><FileText size={24}/><p>{children}</p></div>; }
export function Modal({ title, onClose, children, busy = false }: { title: string; onClose: () => void; children: ReactNode; busy?: boolean }) { return <KnowledgeModal title={title} onClose={onClose} busy={busy} className="kw-modal"><header><h2>{title}</h2><button aria-label="닫기" disabled={busy} onClick={onClose}><X size={18}/></button></header>{children}</KnowledgeModal>; }
export function DocumentRows({ documents, empty = "문서가 없습니다" }: { documents: KnowledgeDocument[]; empty?: string }) { return documents.length ? <div className="kw-doc-rows">{documents.map(doc => <Link href={documentHref(doc)} key={doc.id}><FileText size={17}/><span><strong>{doc.title}</strong><small>{doc.folder || SPACE_LABELS[documentSpace(doc)]} · {kstTime(doc.updated_at)}</small></span><SpaceBadge space={documentSpace(doc)}/></Link>)}</div> : <Empty>{empty}</Empty>; }
export function PinButton({ document }: { document: KnowledgeDocument }) { const { state, command, notify } = useKnowledge(); return <button aria-label="고정핀" aria-pressed={state.pins.includes(document.id)} onClick={() => void command({ action: "pin.toggle", id: document.id }).catch(e => notify(e.message))}><Pin size={16}/></button>; }
export function NewDocumentButton({ space = "team", template, label = "새 문서" }: { space?: "mine" | "team" | "meeting"; template?: Template; label?: string }) { const [open, setOpen] = useState(false); return <><button className="kw-primary" onClick={() => setOpen(true)}><Plus size={15}/>{label}</button>{open && <NewDocumentModal initialSpace={space} initialTemplate={template} close={() => setOpen(false)}/>}</>; }
export function NewDocumentModal({ initialSpace, initialTemplate, close }: { initialSpace: "mine" | "team" | "meeting"; initialTemplate?: Template; close: () => void }) {
  const { actor, state, command, notify } = useKnowledge(), router = useRouter();
  const [space, setSpace] = useState(initialSpace === "team" && actor.memberKind === "partner" ? "mine" : initialSpace);
  const [title, setTitle] = useState(""), [templateId, setTemplateId] = useState(initialTemplate?.id ?? ""), [busy, setBusy] = useState(false), [error, setError] = useState("");
  async function save() { setBusy(true); setError(""); try { const template = state.templates.find(t => t.id === templateId); const result = await command({ action: space === "meeting" ? "meeting.create" : "document.create", space, title: title.trim() || (space === "meeting" ? "" : template?.name ?? "제목 없음"), content: template?.body_md ?? "", templateName: template?.name, visibility: actor.memberKind==="partner"||template?.name === "1:1" ? "attendees" : "team" }); close(); notify(space === "mine" ? "내 노트에 만들었습니다 — 나만 봅니다" : space === "meeting" ? "회의록을 만들었습니다 — 준비 상태" : "팀 문서에 만들었습니다 — 입력하면 자동 저장"); router.push(`/knowledge/${space === "meeting" ? "meetings" : "doc"}/${result.id}`); } catch (e) { setError(e instanceof Error ? e.message : "만들지 못했습니다."); } finally { setBusy(false); } }
  return <Modal title="새 문서" onClose={close} busy={busy}><form onSubmit={e => { e.preventDefault(); void save(); }}><p>어디에 만들까요? 회사 정본은 팀 문서를 정본 후보로 올려 승인받습니다.</p><fieldset className="kw-space-options"><legend>공간</legend>{(["mine", "team", "meeting"] as const).map(value => <label key={value}><input type="radio" name="space" checked={space === value} disabled={value === "team" && actor.memberKind === "partner"} onChange={() => setSpace(value)}/><strong>{value === "meeting" ? "회의록" : SPACE_LABELS[value]}</strong><small>{value === "mine" ? "나만 봅니다. 메모·초안" : value === "team" ? actor.memberKind === "partner" ? "파트너는 관리자에게 요청해 주세요" : "팀원 모두 보고 고칩니다" : "팀원 모두 또는 참석자만 봅니다"}</small></label>)}</fieldset><label>제목<input placeholder="제목 없음" value={title} maxLength={space === "meeting" ? 240 : 300} onChange={e => setTitle(e.target.value)}/></label><label>템플릿 (내용만 채웁니다 — 공간은 위에서 고른 곳)<select value={templateId} onChange={e => setTemplateId(e.target.value)}><option value="">빈 문서</option>{state.templates.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{error && <p className="kw-error" role="alert">{error}</p>}<footer><button type="button" disabled={busy} onClick={close}>취소</button><button className="kw-primary" disabled={busy}>{busy ? "만드는 중…" : "만들기"}</button></footer></form></Modal>;
}
export function Card({ title, href, children }: { title: string; href?: string; children: ReactNode }) { return <section className="kw-card"><header><h2>{title}</h2>{href && <Link href={href}>전체 보기 <ArrowUpRight size={12}/></Link>}</header>{children}</section>; }
