"use client";

import { CheckCircle2, CircleAlert, Clipboard, Film, PackageCheck, Play, Scissors, Sparkles, Youtube } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { createRecord, generateContent, listRecords, updateRecord } from "@/lib/api-client";
import type { OsRecord } from "@/lib/record-types";
import { useSession } from "./session-provider";

function metadata<T>(record: OsRecord | null | undefined, key: string, fallback: T): T {
  const value = record?.metadata?.[key]; return value == null ? fallback : value as T;
}

function SourcePicker({ sources, value, onChange }: { sources: OsRecord[]; value: string; onChange: (value: string) => void }) {
  return <select value={value} onChange={(event) => onChange(event.target.value)}><option value="">기준 콘텐츠 선택</option>{sources.map((source) => <option key={source.id} value={source.id}>{source.title}</option>)}</select>;
}

function CandidateList({ title, items }: { title: string; items: Array<Record<string, unknown>> }) {
  return <section className="panel candidate-panel"><div className="panel-header"><div><h2>{title}</h2><p>{items.length}개 후보 · 별표 항목은 저장 후보</p></div></div>{items.length ? <div className="candidate-list">{items.map((item, index) => <article key={`${String(item.text ?? item)}-${index}`}><span>{index + 1}</span><div><strong>{String(item.text ?? item)}</strong>{item.why ? <p>{String(item.why)}</p> : null}{item.hook ? <small>{String(item.hook)}</small> : null}</div><em>{item.picked ? "★" : "☆"}</em></article>)}</div> : <div className="list-empty"><Sparkles size={20} /><span>정본으로 후보를 생성하면 여기에 표시됩니다.</span></div>}</section>;
}

export function ContentPackageWorkspace() {
  const { accessToken, demo } = useSession();
  const [sources, setSources] = useState<OsRecord[]>([]); const [packages, setPackages] = useState<OsRecord[]>([]);
  const [sourceId, setSourceId] = useState(""); const [tab, setTab] = useState<"search" | "title" | "thumbnail" | "saved">("search");
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { if (demo) return; try { const [sourceResult, packageResult] = await Promise.all([listRecords(accessToken, "content_topic", "limit=200"), listRecords(accessToken, "content_package", "limit=200")]); setSources(sourceResult.records); setPackages(packageResult.records.filter((item) => metadata<string>(item, "packageKind", "") === "title_package")); setSourceId((current) => current || sourceResult.records[0]?.id || ""); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "패키징 자료를 불러오지 못했습니다."); } }, [accessToken, demo]);
  useEffect(() => { load(); }, [load]);
  const latest = packages.find((item) => item.parent_id === sourceId) ?? null; const result = metadata<Record<string, unknown>>(latest, "result", {});
  const titles = Array.isArray(result.titles) ? result.titles as Array<Record<string, unknown>> : [];
  const copies = Array.isArray(result.copies) ? result.copies as Array<Record<string, unknown>> : [];
  const prompts = Array.isArray(result.designPrompts) ? result.designPrompts.map((text) => ({ text })) : [];
  const generate = async () => { if (!sourceId) return; setBusy(true); try { const response = await generateContent(accessToken, { action: "title_package", sourceId }); setError(response.queued ? "Claude 연결 대기 작업으로 저장했습니다." : ""); await load(); if (!response.queued) setTab("title"); } catch (reason) { setError(reason instanceof Error ? reason.message : "후보를 생성하지 못했습니다."); } finally { setBusy(false); } };
  return <><header className="page-header"><div className="page-title-group"><span className="eyebrow">TITLE & THUMBNAIL</span><h1>제목·썸네일</h1><p>시장 근거와 회사 패키징 정본으로 제목·카피·디자인 프롬프트를 만듭니다. 이미지는 생성하지 않습니다.</p></div><div className="header-actions"><SourcePicker sources={sources} value={sourceId} onChange={setSourceId} /><button className="primary-button" disabled={!sourceId || busy} onClick={generate}><Sparkles size={15} /> {busy ? "정본 실행 중…" : "이 콘텐츠로 만들기"}</button></div></header>{error ? <div className="inline-alert danger"><CircleAlert size={16} /> {error}</div> : null}<nav className="studio-tabs">{[["search", "검색"], ["title", "제목"], ["thumbnail", "썸네일"], ["saved", "★ 저장함"]].map(([key, label]) => <button className={tab === key ? "active" : ""} key={key} onClick={() => setTab(key as typeof tab)}>{label}</button>)}</nav>{tab === "search" ? <section className="panel studio-manual"><PackageCheck size={28} /><h2>근거 → MAKE → 후보 채택</h2><p>원본 주제와 최근 패키징 기록을 기준으로 생성합니다. 시장 검색 결과 API가 연결되면 상위 제목 20개와 썸네일 8장을 같은 입력 계약으로 사용할 수 있습니다.</p><div className="procedure-chips"><span>과장 금지</span><span>실제 약속만</span><span>일상어</span><span>이미지 생성 안 함</span></div></section> : null}{tab === "title" ? <CandidateList title="제목 후보" items={titles} /> : null}{tab === "thumbnail" ? <div className="studio-two"><CandidateList title="썸네일 카피" items={copies} /><CandidateList title="디자인 프롬프트" items={prompts} /></div> : null}{tab === "saved" ? <div className="studio-two"><CandidateList title="저장한 제목" items={titles.filter((item) => item.picked)} /><CandidateList title="저장한 썸네일 카피" items={copies.filter((item) => item.picked)} /></div> : null}</>;
}

export function ContentShortsWorkspace() {
  const { accessToken, demo, profile } = useSession();
  const [sources, setSources] = useState<OsRecord[]>([]); const [clips, setClips] = useState<OsRecord[]>([]); const [sourceId, setSourceId] = useState("");
  const [count, setCount] = useState(5); const [reframe, setReframe] = useState("pad"); const [captions, setCaptions] = useState(false); const [tighten, setTighten] = useState(false);
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { if (demo) return; try { const [sourceResult, clipResult] = await Promise.all([listRecords(accessToken, "content_topic", "limit=200"), listRecords(accessToken, "content_short", "limit=200")]); setSources(sourceResult.records); setClips(clipResult.records); setSourceId((current) => current || sourceResult.records[0]?.id || ""); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "숏폼 작업을 불러오지 못했습니다."); } }, [accessToken, demo]);
  useEffect(() => { load(); }, [load]);
  const visible = clips.filter((clip) => clip.parent_id === sourceId); const selected = visible.filter((clip) => metadata(clip, "selected", true));
  const propose = async () => { if (!sourceId) return; setBusy(true); try { const response = await generateContent(accessToken, { action: "shorts_proposal", sourceId, count }); setError(response.queued ? "Claude 연결 대기 작업으로 저장했습니다." : ""); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "쇼츠 구간을 제안하지 못했습니다."); } finally { setBusy(false); } };
  const toggle = async (clip: OsRecord) => { try { await updateRecord(accessToken, { id: clip.id, expectedVersion: clip.version, metadata: { ...clip.metadata, selected: !metadata(clip, "selected", true) } }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "채택 상태를 저장하지 못했습니다."); } };
  const requestRender = async () => { if (!selected.length) return; setBusy(true); try { for (const clip of selected) await updateRecord(accessToken, { id: clip.id, expectedVersion: clip.version, status: "ready", stage: "제작대기", progress: 45, metadata: { ...clip.metadata, reframe, captions, tighten, renderState: "queued" } }); await createRecord(accessToken, { recordType: "ai_job", title: `[숏폼 제작] ${sources.find((source) => source.id === sourceId)?.title ?? "원본"}`, description: `승인된 ${selected.length}개 구간을 ffmpeg 워커에서 제작합니다.`, status: "backlog", priority: "high", team: profile?.team || "콘텐츠", parentId: sourceId, metadata: { contentAction: "shorts_render", sourceId, clipIds: selected.map((clip) => clip.id), reframe, captions, tighten }, tags: ["숏폼", "렌더", "승인완료"] }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "제작 작업을 등록하지 못했습니다."); } finally { setBusy(false); } };
  return <><header className="page-header"><div className="page-title-group"><span className="eyebrow">SHORTS EDITOR</span><h1>숏폼 편집</h1><p>먼저 구간만 제안하고 사람이 채택한 구간만 워커에서 렌더합니다. 기본 세로 화면은 원본을 자르지 않는 pad입니다.</p></div><div className="header-actions"><SourcePicker sources={sources} value={sourceId} onChange={setSourceId} /><input type="number" min="1" max="12" value={count} onChange={(event) => setCount(Number(event.target.value))} /><button className="primary-button" disabled={!sourceId || busy} onClick={propose}><Scissors size={15} /> 구간 제안</button></div></header>{error ? <div className="inline-alert danger"><CircleAlert size={16} /> {error}</div> : null}<section className="panel shorts-controls"><div><label>세로 화면<select value={reframe} onChange={(event) => setReframe(event.target.value)}><option value="pad">전체 보존 · 흐린 배경</option><option value="top">상단 확대 · 아래 여백</option><option value="crop">중앙 크롭 · 예외</option></select></label><label><input type="checkbox" checked={captions} onChange={(event) => setCaptions(event.target.checked)} /> 자동 자막 넣기</label><label><input type="checkbox" checked={tighten} onChange={(event) => setTighten(event.target.checked)} /> 무음 줄이기</label></div><button className="primary-button" disabled={!selected.length || busy} onClick={requestRender}><Play size={15} /> 채택 {selected.length}개 제작 요청</button></section><section className="clip-proposals">{visible.map((clip) => <article className={`panel clip-proposal ${metadata(clip, "selected", true) ? "selected" : ""}`} key={clip.id}><header><button onClick={() => toggle(clip)}>{metadata(clip, "selected", true) ? "✓ 채택" : "＋ 채택"}</button><span className={`status-pill status-${clip.status}`}>{clip.stage || clip.status}</span></header><h3>{clip.title}</h3><p>{clip.description}</p><div><span>{Number(metadata(clip, "start", 0)).toFixed(1)}초</span><span>→</span><span>{Number(metadata(clip, "end", 0)).toFixed(1)}초</span></div><small>{metadata<string>(clip, "renderState", "not_started") === "queued" ? "워커 제작 대기" : "렌더 전 제안"}</small></article>)}{!visible.length ? <div className="panel empty-state"><div><span><Film /></span><h3>제안된 구간이 없습니다.</h3><p>원본을 선택하고 구간 제안을 실행하세요. 렌더링은 아직 시작되지 않습니다.</p></div></div> : null}</section></>;
}

const KIT_FIELDS = [["title", "영상 제목"], ["description", "유튜브 설명"], ["tags", "태그"], ["chapters", "챕터"], ["pinnedComment", "고정 댓글"], ["kakao", "카카오톡"], ["cafe", "네이버 카페"], ["post", "게시글"], ["checklist", "업로드 체크리스트"]] as const;

export function YoutubeKitWorkspace() {
  const { accessToken, demo } = useSession(); const [sources, setSources] = useState<OsRecord[]>([]); const [kits, setKits] = useState<OsRecord[]>([]); const [sourceId, setSourceId] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [copied, setCopied] = useState("");
  const load = useCallback(async () => { if (demo) return; try { const [sourceResult, packageResult] = await Promise.all([listRecords(accessToken, "content_topic", "limit=200"), listRecords(accessToken, "content_package", "limit=200")]); setSources(sourceResult.records); setKits(packageResult.records.filter((item) => metadata<string>(item, "packageKind", "") === "youtube_kit")); setSourceId((current) => current || sourceResult.records[0]?.id || ""); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "유튜브 발행 키트를 불러오지 못했습니다."); } }, [accessToken, demo]);
  useEffect(() => { load(); }, [load]); const kit = kits.find((item) => item.parent_id === sourceId) ?? null; const result = metadata<Record<string, unknown>>(kit, "result", {});
  const generate = async () => { if (!sourceId) return; setBusy(true); try { const response = await generateContent(accessToken, { action: "youtube_kit", sourceId }); setError(response.queued ? "Claude 연결 대기 작업으로 저장했습니다." : ""); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "발행 키트를 만들지 못했습니다."); } finally { setBusy(false); } };
  const copy = async (key: string, value: unknown) => { await navigator.clipboard.writeText(Array.isArray(value) ? value.join("\n") : String(value ?? "")); setCopied(key); setTimeout(() => setCopied(""), 1200); };
  return <><header className="page-header"><div className="page-title-group"><span className="eyebrow">YOUTUBE PUBLISHING KIT</span><h1>유튜브 관리</h1><p>롱폼 원고와 발행 절차 정본을 조립해 설명·태그·챕터·홍보 문구를 한 번에 준비합니다. 실제 업로드는 별도 발행기가 담당합니다.</p></div><div className="header-actions"><SourcePicker sources={sources} value={sourceId} onChange={setSourceId} /><button className="primary-button" disabled={!sourceId || busy} onClick={generate}><Youtube size={15} /> {busy ? "조립 중…" : "발행 키트 만들기"}</button></div></header>{error ? <div className="inline-alert danger"><CircleAlert size={16} /> {error}</div> : null}<section className="kit-grid">{KIT_FIELDS.map(([key, label]) => { const value = result[key]; return <article className="panel kit-card" key={key}><header><div><PackageCheck size={15} /><strong>{label}</strong></div><button className="ghost-button" disabled={!value} onClick={() => copy(key, value)}><Clipboard size={13} /> {copied === key ? "복사됨" : "복사"}</button></header><pre>{Array.isArray(value) ? value.join("\n") : String(value ?? "생성된 내용이 없습니다.")}</pre></article>; })}</section>{kit ? <div className="inline-alert success"><CheckCircle2 size={16} /> 최종 승인 전 편집 가능한 발행 키트입니다. 외부 업로드는 실행되지 않았습니다.</div> : null}</>;
}
