"use client";

import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import Link from "next/link";
import { archiveRecord, createDocument, createRecord, listAllRecordsOfType, updateRecord } from "@/lib/api-client";
import { dedupeMetricSnapshots, fixedWeek, groupMetricDimension, metricDisplay, metricValue, summarizeMetrics } from "@/lib/content-metrics";
import type { OsRecord } from "@/lib/record-types";
import { useSession } from "./session-provider";

const METRICS = [{ key: "views", label: "조회", suffix: "" }, { key: "ctr", label: "노출 가중 CTR", suffix: "%" }, { key: "retention", label: "조회 가중 지속률", suffix: "%" }, { key: "purchases", label: "구매", suffix: "" }, { key: "revenue", label: "기여 매출", suffix: "원" }, { key: "subscribers", label: "구독자 순증", suffix: "" }] as const;
const FIELDS = [{ key: "impressions", label: "노출" }, { key: "views", label: "조회" }, { key: "clicks", label: "클릭" }, { key: "ctr", label: "CTR %" }, { key: "retention", label: "시청지속률 %" }, { key: "subscribers", label: "구독자 순증" }, { key: "purchases", label: "구매" }, { key: "revenue", label: "기여 매출 (원)" }];
const today = () => new Date().toISOString().slice(0, 10);
const text = (form: FormData, key: string) => String(form.get(key) ?? "").trim();

export function ContentPerformanceDashboard() {
  const { accessToken, demo, profile } = useSession();
  const [records, setRecords] = useState<OsRecord[]>([]); const [hypotheses, setHypotheses] = useState<OsRecord[]>([]);
  const [brand, setBrand] = useState("all"); const [platform, setPlatform] = useState("all"); const [hierarchy, setHierarchy] = useState("all");
  const [from, setFrom] = useState(new Date(Date.now() - 29 * 86400000).toISOString().slice(0, 10)); const [to, setTo] = useState(today());
  const [dimension, setDimension] = useState("video"); const [weekA, setWeekA] = useState(""); const [weekB, setWeekB] = useState("");
  const [editing, setEditing] = useState<OsRecord | null>(null); const [open, setOpen] = useState(false);
  const [hypothesis, setHypothesis] = useState(""); const [hypothesisEdit, setHypothesisEdit] = useState<OsRecord | null>(null);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [reportId, setReportId] = useState("");
  const load = useCallback(async () => {
    if (demo) return;
    const [metrics, decisions] = await Promise.all([listAllRecordsOfType(accessToken, "content_metric"), listAllRecordsOfType(accessToken, "decision")]);
    setRecords(metrics); setHypotheses(decisions.filter((item) => item.metadata.kind === "content_hypothesis"));
  }, [accessToken, demo]);
  useEffect(() => { load().catch((reason) => setError(reason.message)); }, [load]);
  const perform = async (action: () => Promise<unknown>) => { setBusy(true); setError(""); try { await action(); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "저장하지 못했습니다."); } finally { setBusy(false); } };
  const scope = useMemo(() => records.filter((item) => (brand === "all" || item.brand === brand) && (platform === "all" || item.metadata.platform === platform) && (hierarchy === "all" || item.metadata.hierarchy === hierarchy)), [records, brand, platform, hierarchy]);
  const filtered = useMemo(() => dedupeMetricSnapshots(scope.filter((item) => { const date = (item.starts_at ?? item.created_at).slice(0, 10); return date >= from && date <= to; })), [scope, from, to]);
  const totals = summarizeMetrics(filtered);
  const daily = groupMetricDimension(filtered.filter((record) => record.metadata.metricMode !== "cumulative").map((record) => ({ ...record, metadata: { ...record.metadata, day: (record.starts_at ?? record.created_at).slice(0, 10) } })), "day").sort((a, b) => a.title.localeCompare(b.title));
  const groups = groupMetricDimension(filtered, dimension).sort((a, b) => (b.revenue ?? -1) - (a.revenue ?? -1));
  const compare = [weekA, weekB].map((start) => { const week = fixedWeek(start); const data = week ? dedupeMetricSnapshots(scope.filter((item) => { const date = (item.starts_at ?? item.created_at).slice(0, 10); return date >= week.start && date <= week.end; })) : []; return { week, count: data.length, totals: summarizeMetrics(data) }; });
  const save = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    await perform(async () => {
      const numeric = Object.fromEntries(FIELDS.map(({ key }) => [key, text(form, key) === "" ? null : Number(text(form, key))]));
      const payload = { title: text(form, "title"), description: text(form, "note"), status: "measuring", brand: text(form, "brand"), team: profile?.team || "콘텐츠", sourceUrl: text(form, "sourceUrl") || null, startsAt: `${text(form, "date")}T12:00:00Z`, metricCurrent: numeric.views, metricUnit: "조회", metadata: { ...(editing?.metadata ?? {}), ...numeric, platform: text(form, "platform"), hierarchy: text(form, "hierarchy"), topic: text(form, "topic"), hookType: text(form, "hookType"), traffic: text(form, "traffic"), contentId: text(form, "contentId"), metricMode: text(form, "metricMode"), dataSource: "manual", measuredAt: new Date().toISOString() } };
      if (editing) await updateRecord(accessToken, { id: editing.id, expectedVersion: editing.version, ...payload }); else await createRecord(accessToken, { recordType: "content_metric", ...payload });
      setOpen(false); setEditing(null);
    });
  };
  const saveHypothesis = () => perform(async () => {
    const metadata = { ...(hypothesisEdit?.metadata ?? {}), kind: "content_hypothesis", periodFrom: from, periodTo: to, brandFilter: brand, platformFilter: platform, hierarchyFilter: hierarchy, sampleCount: filtered.length };
    if (hypothesisEdit) await updateRecord(accessToken, { id: hypothesisEdit.id, expectedVersion: hypothesisEdit.version, title: hypothesis.slice(0, 240), description: hypothesis, status: "review", metadata });
    else await createRecord(accessToken, { recordType: "decision", title: hypothesis.slice(0, 240), description: hypothesis, status: "review", stage: "콘텐츠 가설", metadata });
    setHypothesis(""); setHypothesisEdit(null);
  });
  const weeklyReport = () => perform(async () => {
    const { document } = await createDocument(accessToken, { title: `콘텐츠 성과 검토 ${from} ~ ${to}`, folder: "콘텐츠/성과/주간리포트", tags: ["콘텐츠", "주간리포트"], content: `# 콘텐츠 성과 검토\n\n기간: ${from} ~ ${to} · 브랜드: ${brand} · 채널: ${platform} · 위계: ${hierarchy}\n\n## 1. 확인한 사실\n표본 ${filtered.length}건. ${METRICS.map((item) => `${item.label}: ${metricDisplay(totals[item.key], item.suffix)}`).join(" · ")}\n\n## 2. 검토할 가설\n${hypotheses.filter((item) => item.status === "review").map((item) => `- ${item.description}`).join("\n") || "- 등록된 가설 없음"}\n\n## 3. 다음 주 실험\n- A/B 기간, 대상 영상, 변경 변수와 성공 기준을 사람이 입력\n\n## 4. 사람 판정\n- 채택 / 폐기 / 관찰 / 수정 결정 대기\n- 미연결 값은 0으로 해석하지 않음. 자동 정본 반영·외부 발행 없음.\n` }); setReportId(document.id);
  });
  return <>
    <header className="page-header"><div className="page-title-group"><h1>영상 성과</h1><p>실측 성과를 비교하고 다음 제작 가설을 검토합니다. 빈 값은 미연결로 표시합니다.</p></div><div className="header-actions"><button className="secondary-button" disabled={busy} onClick={() => void perform(load)}>새로고침</button><button className="secondary-button" disabled={busy || !filtered.length} onClick={weeklyReport}>주간리포트 초안</button><button className="primary-button" onClick={() => { setEditing(null); setOpen(true); }}>성과 기록</button></div></header>
    {error ? <p className="inline-alert danger" role="alert">{error}</p> : null}{reportId ? <p className="inline-alert success"><Link href={`/knowledge?document=${reportId}`}>저장된 주간리포트 열기</Link></p> : null}
    <section className="panel content-performance-filters"><label>브랜드<select value={brand} onChange={(event) => setBrand(event.target.value)}><option value="all">전체</option>{[...new Set(records.map((item) => item.brand).filter(Boolean))].map((value) => <option key={value}>{value}</option>)}</select></label><label>플랫폼<select value={platform} onChange={(event) => setPlatform(event.target.value)}><option value="all">전체</option>{[...new Set(records.map((item) => String(item.metadata.platform ?? "")).filter(Boolean))].map((value) => <option key={value}>{value}</option>)}</select></label><label>위계<select value={hierarchy} onChange={(event) => setHierarchy(event.target.value)}><option value="all">전체</option>{["유입형", "전환형", "판매형"].map((value) => <option key={value}>{value}</option>)}</select></label><label>시작<input type="date" value={from} max={to} onChange={(event) => setFrom(event.target.value)} /></label><label>종료<input type="date" value={to} min={from} onChange={(event) => setTo(event.target.value)} /></label></section>
    <p className="metric-caption">중복 측정 제거 후 {filtered.length}건 · 누적 측정은 영상별 최신 값 사용 · 비율은 노출·조회 수가 있는 기록으로 계산</p>
    <section className="metric-grid content-performance-metrics">{METRICS.map((item) => <div className="metric-card" key={item.key}><div className="metric-top">{item.label}</div><div className="metric-value">{metricDisplay(totals[item.key], item.suffix)}</div><small>측정 {filtered.filter((record) => metricValue(record, item.key) !== null).length}/{filtered.length}건</small></div>)}</section>
    <section className="performance-analysis-grid"><article className="panel pipeline-panel"><h2>일별 조회 흐름</h2><p>당일 증가분 기록만 표시합니다. 누적 스냅샷은 합산하지 않습니다.</p>{daily.slice(-14).map((day) => <p key={day.key}>{day.title} · {metricDisplay(day.views)}회</p>)}{!daily.length ? <p>당일 증가분 기록이 없습니다.</p> : null}</article><article className="panel pipeline-panel"><h2>콘텐츠 전환 퍼널</h2><p>선택 기간 실측값 · 미연결 구간은 판정 보류</p>{[["노출", totals.impressions], ["조회", totals.views], ["클릭", totals.clicks], ["구매", totals.purchases]].map(([label, value]) => <p key={String(label)}>{label}: {metricDisplay(value as number | null)}</p>)}</article></section>
    <section className="panel performance-table"><div className="panel-header"><h2>성과 비교</h2><label>묶음 기준<select value={dimension} onChange={(event) => setDimension(event.target.value)}>{[["video", "영상"], ["hierarchy", "위계"], ["topic", "주제"], ["hookType", "훅 형식"], ["traffic", "유입원"]].map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label></div><table><thead><tr><th>구분</th><th>측정</th>{METRICS.map((item) => <th key={item.key}>{item.label}</th>)}</tr></thead><tbody>{groups.map((group) => <tr key={group.key}><td>{group.title}</td><td>{group.count}</td>{METRICS.map((item) => <td key={item.key}>{metricDisplay(group[item.key], item.suffix)}</td>)}</tr>)}</tbody></table>{!groups.length ? <p className="small-empty">선택 기간에 측정된 성과가 없습니다.</p> : null}</section>
    <section className="panel pipeline-panel"><h2>A/B 주차 비교</h2><p>두 주의 시작일을 고정하면 각각 7일을 비교합니다. 표본 수와 누락을 확인한 뒤 사람이 판정합니다.</p><div className="form-grid"><label>A 주 시작<input type="date" value={weekA} onChange={(event) => setWeekA(event.target.value)} /></label><label>B 주 시작<input type="date" value={weekB} onChange={(event) => setWeekB(event.target.value)} /></label></div><div className="form-grid">{compare.map((item, index) => <article key={index}><strong>{index ? "B" : "A"} · {item.week ? `${item.week.start} ~ ${item.week.end}` : "기간 선택"}</strong><p>표본 {item.count}건</p>{METRICS.map((metric) => <p key={metric.key}>{metric.label}: {metricDisplay(item.totals[metric.key], metric.suffix)}</p>)}</article>)}</div></section>
    <section className="panel pipeline-panel"><h2>다음 제작 가설</h2><p>현재 필터의 측정 기간과 표본 수를 함께 저장합니다. 가설 수정 시 다시 검토 상태가 됩니다.</p><textarea aria-label="가설 내용" value={hypothesis} onChange={(event) => setHypothesis(event.target.value)} rows={3} /><button className="primary-button" disabled={busy || !hypothesis.trim()} onClick={saveHypothesis}>{hypothesisEdit ? "가설 수정 저장" : "가설 추가"}</button>{hypotheses.map((item) => <article className="hypothesis-row" key={item.id}><p>{item.description}</p><small>{String(item.metadata.periodFrom ?? "")} ~ {String(item.metadata.periodTo ?? "")} · 표본 {String(item.metadata.sampleCount ?? "미정")}</small><div className="pipeline-actions"><select aria-label={`${item.title} 판정`} disabled={busy} value={item.status} onChange={(event) => { const status = event.target.value; void perform(() => updateRecord(accessToken, { id: item.id, expectedVersion: item.version, status, metadata: { ...item.metadata, decidedAt: new Date().toISOString(), decidedBy: profile?.id } })); }}>{[["review", "검토 대기"], ["adopted", "채택"], ["discarded", "폐기"], ["observing", "관찰"], ["revising", "수정"]].map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><button className="ghost-button" onClick={() => { setHypothesisEdit(item); setHypothesis(item.description); }}>수정</button><button className="ghost-button" disabled={busy} onClick={() => void perform(() => archiveRecord(accessToken, item.id))}>휴지통</button></div></article>)}</section>
    <section className="panel performance-table"><div className="panel-header"><h2>측정 기록</h2></div><table><thead><tr><th>영상</th><th>기준일</th><th>출처</th><th>측정 방식</th><th>관리</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td>{item.title}</td><td>{(item.starts_at ?? item.created_at).slice(0, 10)}</td><td>{String(item.metadata.dataSource ?? "출처 미입력")}</td><td>{item.metadata.metricMode === "cumulative" ? "누적" : "당일"}</td><td><button className="ghost-button" onClick={() => { setEditing(item); setOpen(true); }}>수정</button><button className="ghost-button" disabled={busy} onClick={() => void perform(() => archiveRecord(accessToken, item.id))}>휴지통</button></td></tr>)}</tbody></table></section>
    {open ? <div className="drawer-backdrop"><form className="record-drawer" key={editing?.id ?? "new"} onSubmit={save}><div className="drawer-head"><h2>{editing ? "영상 성과 수정" : "영상 성과 기록"}</h2><button type="button" className="ghost-button" disabled={busy} onClick={() => setOpen(false)}>닫기</button></div><p>확인하지 못한 수치는 비워 두세요. 0은 실제 측정값으로 저장됩니다.</p><label>영상 제목<input required name="title" defaultValue={editing?.title} /></label><label>브랜드<input name="brand" defaultValue={editing?.brand || "브랜디액션"} /></label><label>측정일<input type="date" required name="date" defaultValue={editing ? (editing.starts_at ?? editing.created_at).slice(0, 10) : today()} /></label><label>콘텐츠 ID 또는 YouTube 영상 ID<input name="contentId" defaultValue={String(editing?.metadata.contentId ?? "")} /></label><label>영상 URL<input type="url" name="sourceUrl" defaultValue={editing?.source_url ?? ""} /></label><div className="form-grid"><label>플랫폼<select name="platform" defaultValue={String(editing?.metadata.platform ?? "YouTube")}>{["YouTube", "YouTube Shorts", "Instagram", "Threads"].map((value) => <option key={value}>{value}</option>)}</select></label><label>측정 방식<select name="metricMode" defaultValue={String(editing?.metadata.metricMode ?? "daily")}><option value="daily">해당 날짜 증가분</option><option value="cumulative">측정 시점 누적값</option></select></label></div><label>위계<select name="hierarchy" defaultValue={String(editing?.metadata.hierarchy ?? "유입형")}>{["유입형", "전환형", "판매형"].map((value) => <option key={value}>{value}</option>)}</select></label><div className="form-grid">{FIELDS.map((field) => <label key={field.key}>{field.label}<input type="number" step="any" name={field.key} min={field.key === "subscribers" ? undefined : 0} max={["ctr", "retention"].includes(field.key) ? 100 : undefined} defaultValue={editing ? metricValue(editing, field.key) ?? "" : ""} /></label>)}</div>{[["topic", "주제"], ["hookType", "훅 형식"], ["traffic", "유입원"]].map(([key, label]) => <label key={key}>{label}<input name={key} defaultValue={String(editing?.metadata[key] ?? "")} /></label>)}<label>판정 메모<textarea name="note" defaultValue={editing?.description} /></label><div className="drawer-actions"><button type="button" className="secondary-button" disabled={busy} onClick={() => setOpen(false)}>취소</button><button className="primary-button" disabled={busy}>성과 저장</button></div></form></div> : null}
  </>;
}
