"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { apiRequest, listMembers } from "@/lib/api-client";
import { COMMENT_KINDS, commentStatusLabel, mayHideComment } from "@/lib/content-comments";
import type { OsRecord } from "@/lib/record-types";
import { demoRecord } from "@/lib/demo-record";
import { useSession } from "./session-provider";
import { PageTitle } from "./page-title";
import { useContentWork } from "./content-work-provider";
import { ContentGenerationButton } from "./content-generation-button";
type CommentRow=OsRecord&{canRespond:boolean;teamShared:boolean};
const tabs=[["unanswered","답할 것"],["question","질문"],["spam","스팸 의심"],["mine","내 담당"],["replied","답함"],["hidden","숨김"]];
export function ContentCommentsWorkspace(){
  const {accessToken,profile,demo}=useSession();
  const work=useContentWork();
  const [rows,setRows]=useState<CommentRow[]>([]),[members,setMembers]=useState<{id:string;display_name:string}[]>([]),[tab,setTab]=useState("unanswered"),[account,setAccount]=useState("all");
  const [selected,setSelected]=useState(""),[reply,setReply]=useState(""),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(!demo),[error,setError]=useState(""),[notice,setNotice]=useState(""),[truncated,setTruncated]=useState(false);
  const load=useCallback(async()=>{if(demo){setMembers(profile?[{id:profile.id,display_name:"나"}]:[]);return;}setLoading(true);try{const [result,people]=await Promise.all([apiRequest<{comments:CommentRow[];truncated:boolean}>("/api/v1/content/comments",{token:accessToken}),listMembers(accessToken)]);setRows(result.comments);setTruncated(result.truncated);setMembers(people.members.filter(person=>person.is_active));}catch(reason){setError(reason instanceof Error?reason.message:"댓글 조회 실패");}finally{setLoading(false);}},[accessToken,demo,profile]);
  useEffect(()=>{void load();},[load]);
  const current=rows.find(row=>row.id===selected);
  async function action(row:CommentRow,operation:string,extra:Record<string,unknown>={}){
    setBusy(true);setError("");setNotice("");
    try{
      if(demo){
        if(["reply","hide"].includes(operation)&&!row.canRespond)throw Error("비공유 계정은 연결한 본인만 처리할 수 있습니다.");
        if(operation==="draft"){setReply("질문 감사합니다. 구체적인 업무 상황을 알려 주시면 확인한 기준으로 안내하겠습니다.");setConfirmed(false);setNotice(extra.mode==="api"?"모의 API 초안 · 실제 API 호출 없음":"모의 대기열 요청 · 실제 작업 저장 없음");return;}
        if(operation==="topic"){setNotice("모의 주제 초안을 만들었습니다. 실제 데이터 저장은 없습니다.");return;}
        const updated=demoRecord({...(operation==="assign"?{assigneeId:extra.assigneeId}:{}),status:operation==="reply"?"replied":operation==="hide"?"hidden":row.status,metadata:{...row.metadata,...(operation==="classify"?{kind:extra.kind}:{}),...(["reply","hide"].includes(operation)?{reply:extra.text??"",handledBy:profile?.id,handledAt:new Date().toISOString(),mockAction:true}: {})}},profile?.id??"demo",row);
        setRows(old=>old.map(item=>item.id===row.id?{...updated,canRespond:row.canRespond,teamShared:row.teamShared}:item));setConfirmed(false);setNotice("모의 처리 완료 · 외부 전송 없음");return;
      }
      const result=await apiRequest<{comment?:OsRecord;queued?:boolean;topicId?:string}>("/api/v1/content/comments",{method:"POST",token:accessToken,body:JSON.stringify({id:row.id,expectedVersion:row.version,operation,...extra})});
      if(result.comment){setRows(old=>old.map(item=>item.id===row.id?{...result.comment!,canRespond:row.canRespond,teamShared:row.teamShared}:item));if(operation==="draft")setReply(String(result.comment.metadata.replyDraft??""));}
      setConfirmed(false);setNotice(result.queued?"구독 대기열에 넣었습니다. AI 작업에서 진행을 확인하세요.":result.topicId?"주제·기획에 초안을 저장했습니다.":"처리 결과를 저장했습니다.");
    }catch(reason){setError(reason instanceof Error?reason.message:"댓글 처리 실패");}finally{setBusy(false);}
  }
  const keys=[...new Set(rows.map(row=>`${row.metadata.platform}:${row.metadata.connectionOwnerId}`))];
  const scoped=rows.filter(row=>(!work?.topicId||row.metadata.sourceTopicId===work.topicId||work.publications.some(post=>post.id===row.parent_id&&post.parent_id===work.topicId))&&(account==="all"||`${row.metadata.platform}:${row.metadata.connectionOwnerId}`===account));
  const matchesTab=(row:CommentRow,value:string)=>value==="mine"?row.assignee_id===profile?.id:value==="question"||value==="spam"?row.metadata.kind===value:row.status===value;
  const filtered=scoped.filter(row=>matchesTab(row,tab));
  const groups=[...new Set(filtered.map(row=>row.parent_id))];
  function examples(){const owner=profile?.id??"demo";setRows([0,1,2].map(index=>({...demoRecord({recordType:"content_comment",title:"모의 댓글",description:index===2?"답글의 답글입니다.":"첫 단계부터 적용하려면 무엇을 준비하면 될까요?",status:"unanswered",parentId:`demo-post-${index===1?2:1}`,metadata:{sourceTopicId:"demo-final-topic",platform:index===1?"instagram":"threads",connectionOwnerId:index===1?"demo-other":owner,author:"모의 시청자",postTitle:index===1?"다른 계정의 카드뉴스":"예시 콘텐츠",kind:"question",topLevel:index!==2}},owner),canRespond:index!==1,teamShared:false})));setSelected("");}
  return <><header className="page-header"><div className="page-title-group"><PageTitle/><p>최근 14일 게시물의 댓글을 확인하고, 답변은 사람이 검토한 뒤 보냅니다.</p></div><Link className="secondary-button" href="/settings/account">채널 연결</Link></header>
    {demo?<button className="secondary-button" onClick={examples}>모의 댓글 불러오기 · 외부 저장 없음</button>:<button className="secondary-button" disabled={loading||busy} onClick={()=>void load()}>새로고침</button>}
    {error?<p className="inline-alert danger" role="alert">{error}</p>:null}{notice?<p className="inline-alert" role="status">{notice}</p>:null}
    <nav className="studio-tabs" aria-label="댓글 보기">{tabs.map(([value,label])=><button key={value} aria-pressed={tab===value} className={tab===value?"active":""} onClick={()=>{setTab(value);setSelected("");}}>{label}<span className="comment-tab-count">{loading?"…":scoped.filter(row=>matchesTab(row,value)).length}</span></button>)}</nav>
    <label className="comment-account-filter">게시 계정<select value={account} onChange={event=>{setAccount(event.target.value);setSelected("");}}><option value="all">전체 계정</option>{keys.map((key,index)=>{const row=rows.find(item=>`${item.metadata.platform}:${item.metadata.connectionOwnerId}`===key)!;return <option key={key} value={key}>{String(row.metadata.platform)} · {row.teamShared?"팀 공유":row.canRespond?"내 채널":"보기 전용"} {index+1}</option>;})}</select></label>
    {loading?<div className="panel loading-state" role="status">댓글 불러오는 중…</div>:<div className="comments-workspace"><section>{groups.map(group=><article className="panel comment-post" key={group}><header><h2>{String(filtered.find(row=>row.parent_id===group)?.metadata.postTitle??"게시물 댓글")}</h2>{group&&!demo?<Link href={`/content/publishing?tab=review&publication=${encodeURIComponent(group)}`}>게시물 보기 →</Link>:null}</header>{filtered.filter(row=>row.parent_id===group).map(row=><div className="comment-row" data-selected={selected===row.id} key={row.id}><div><span>{String(row.metadata.author??"시청자")} · {String(row.metadata.platform)} · {row.teamShared?"팀 공유":row.canRespond?"내 채널":"비공유 · 보기 전용"}</span><p>{row.description}</p><small>{commentStatusLabel(row.status)}{row.metadata.mock?" · 모의 수집":""}</small>{row.metadata.handledAt?<small>처리 기록 있음 · {new Date(String(row.metadata.handledAt)).toLocaleString("ko-KR")}</small>:null}</div><div className="comment-row-actions"><label>분류<select aria-label={`${row.title} 분류`} disabled={busy} value={String(row.metadata.kind??"unclassified")} onChange={event=>void action(row,"classify",{kind:event.target.value})}>{Object.entries(COMMENT_KINDS).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>담당<select aria-label={`${row.title} 담당`} disabled={busy} value={row.assignee_id??""} onChange={event=>void action(row,"assign",{assigneeId:event.target.value||null})}><option value="">미지정</option>{members.map(person=><option value={person.id} key={person.id}>{person.display_name}</option>)}</select></label><button className="secondary-button" onClick={()=>{setSelected(row.id);setReply(String(row.metadata.replyDraft??row.metadata.reply??""));setConfirmed(false);}}>답글 · 처리</button><button className="ghost-button" disabled={busy} onClick={()=>void action(row,"topic")}>① 주제·기획으로 보내기</button>{typeof row.metadata.topicId==="string"?<Link href={`/content/topics?topic=${encodeURIComponent(row.metadata.topicId)}`}>주제 초안 열기</Link>:null}</div></div>)}</article>)}{!filtered.length?<div className="panel empty-state"><p>이 보기에 해당하는 댓글이 없습니다. 수집은 연결·DB 준비 후 시간별로 실행됩니다.</p></div>:null}{truncated?<p>최근 200건만 표시합니다. 이전 댓글은 다음 조회 기능이 필요합니다.</p>:null}</section>
    {current?<aside className="panel comment-composer"><header><h2>답글·처리</h2><button className="ghost-button" onClick={()=>setSelected("")}>닫기</button></header><blockquote>{current.description}</blockquote>{!current.canRespond?<p className="inline-alert">비공유 계정입니다. 연결한 본인만 답글·숨기기를 할 수 있습니다.</p>:null}<ContentGenerationButton disabled={busy||current.status!=="unanswered"} onGenerate={mode=>void action(current,"draft",{mode})}>답글 초안 대기열</ContentGenerationButton><label>답글 내용<textarea value={reply} onChange={event=>{setReply(event.target.value);setConfirmed(false);}} maxLength={500} rows={6}/></label><small>{Array.from(reply).length}/500자 · 전송 전 직접 수정해 주세요.</small><label><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>답글·숨기기 대상을 확인했습니다.</label><button className="primary-button" disabled={busy||!current.canRespond||!confirmed||!reply.trim()||current.status!=="unanswered"} onClick={()=>void action(current,"reply",{text:reply,confirm:true})}>{demo?"모의 답글 보내기":"확인하고 답글 보내기"}</button><button className="secondary-button" disabled={busy||!current.canRespond||!confirmed||current.status!=="unanswered"||!mayHideComment(String(current.metadata.platform),current.metadata.topLevel===true)} onClick={()=>void action(current,"hide",{confirm:true})}>{demo?"모의 숨기기":"확인하고 숨기기"}</button>{!mayHideComment(String(current.metadata.platform),current.metadata.topLevel===true)?<small>Threads의 중첩 답글은 숨길 수 없습니다.</small>:null}<Link href="/organization/agents">초안 작업 진행 확인 →</Link></aside>:<aside className="panel comment-empty-composer"><h2>댓글을 선택해 주세요</h2><p>왼쪽 댓글에서 ‘답글 · 처리’를 누르면<br/>여기에서 초안을 작성하고 확인할 수 있습니다.</p></aside>}</div>}
  </>;
}
