"use client";
import { useState } from "react";
import { changedLineRange } from "@/lib/knowledge-graph-view";
import { KnowledgeModal } from "./knowledge-modal";
export function KnowledgeVersionComparison({title,left,right,action,busy,error,onAction,onClose}: {title:string;left:{label:string;title:string;content:string;properties?:Record<string,string>};right:{label:string;title:string;content:string;properties?:Record<string,string>};action:string;busy:boolean;error:string;onAction:()=>void;onClose:()=>void}) {
  const [copyMessage,setCopyMessage]=useState("");
  const diff=changedLineRange(left.content,right.content);
  return <KnowledgeModal title={title} onClose={onClose} busy={busy}><div className="form-modal p2-version-modal"><header><h2>{title}</h2><button disabled={busy} aria-label="비교 닫기" onClick={onClose}>×</button></header><div className="p2-comparison-body"><p>{diff.same?"본문이 같습니다.":`${diff.start}번째 줄부터 변경 구간: 왼쪽 ${diff.removed.length}줄 / 오른쪽 ${diff.added.length}줄`}{left.title!==right.title?" · 제목 변경됨":""}</p><p>변경 구간은 첫 차이부터 마지막 차이까지입니다. 양쪽 전체 내용을 확인할 수 있습니다.</p><div className="p2-comparison">{[left,right].map((side,index)=><section key={index}><h3>{side.label}</h3><strong>{side.title}</strong>{side.properties ? <dl>{Object.entries(side.properties).map(([label,value]) => <div key={label}><dt>{label}</dt><dd>{value || "없음"}</dd></div>)}</dl> : null}<textarea aria-label={`${side.label} 본문`} value={side.content} readOnly spellCheck={false}/><button className="secondary-button" onClick={async()=>{try{await navigator.clipboard.writeText(side.content);setCopyMessage(`${side.label} 본문을 복사했습니다.`);}catch{setCopyMessage("본문을 선택해 직접 복사해 주세요.");}}}>본문 복사</button></section>)}</div>{copyMessage?<p role="status">{copyMessage}</p>:null}{error?<p role="alert" className="inline-alert danger">{error}</p>:null}</div><footer><button className="secondary-button" disabled={busy} onClick={onClose}>닫기</button><button className="primary-button" disabled={busy} onClick={onAction}>{busy?"처리 중…":action}</button></footer></div></KnowledgeModal>;
}
