"use client";

import { Activity, Bot, CheckCircle2, CircleAlert, Database, KeyRound, MessageSquareText, RefreshCw, Search, ShieldCheck } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { getHealth, listDocuments, listRecords } from "@/lib/api-client";
import type { OsRecord } from "@/lib/record-types";
import { useSession } from "./session-provider";

export function MonitoringWorkspace() {
  const { accessToken, demo } = useSession();
  const [health, setHealth] = useState<Awaited<ReturnType<typeof getHealth>> | null>(null);
  const [connections, setConnections] = useState<OsRecord[]>([]);
  const [documents, setDocuments] = useState(0);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const load = useCallback(async () => { if (demo) return; setLoading(true); try { const [status, connectionResult, documentResult] = await Promise.all([getHealth(), listRecords(accessToken, "connection", "limit=200"), listDocuments(accessToken, "limit=1")]); setHealth(status); setConnections(connectionResult.records); setDocuments(documentResult.total); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "운영 상태를 확인하지 못했습니다."); } finally { setLoading(false); } }, [accessToken, demo]);
  useEffect(() => { load(); }, [load]);
  const status = (ready: boolean, title: string, description: string, icon: React.ReactNode) => <article className="panel service-status"><span className={ready ? "ready" : "waiting"}>{icon}</span><div><strong>{title}</strong><p>{description}</p></div><em className={ready ? "ready" : "waiting"}>{ready ? "정상" : "대기"}</em></article>;
  return <><header className="page-header"><div className="page-title-group"><span className="eyebrow">OPERATIONS MONITORING</span><h1>운영 모니터링</h1><p>DB·인증·검색·메시지 연결과 내부 데이터 준비 상태를 점검합니다.</p></div><button className="secondary-button" disabled={loading} onClick={load}><RefreshCw size={15} className={loading ? "spin" : ""} /> 새로 확인</button></header>{error ? <div className="inline-alert danger"><CircleAlert size={16} /> {error}</div> : null}<section className="monitor-summary panel"><span className={health?.ok ? "healthy" : "partial"}><Activity size={20} /></span><div><strong>{health?.ok ? "핵심 서버 정상" : "핵심 서버 확인 필요"}</strong><p>{health?.checkedAt ? new Intl.DateTimeFormat("ko-KR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(health.checkedAt)) : "확인 중"}</p></div><small>지식 문서 {documents.toLocaleString("ko-KR")}개 · 외부 연결 {connections.length}개</small></section><section className="service-grid">{status(health?.database === "ready", "Supabase Database", health?.database === "ready" ? "운영 기록·지식 테이블 응답 정상" : "서비스 키 또는 DB 응답 확인 필요", <Database size={18} />)}{status(health?.auth === "ready", "Supabase Auth", health?.auth === "ready" ? "이메일·비밀번호 세션 사용 가능" : "공개 인증 설정 누락", <KeyRound size={18} />)}{status(health?.embeddings === "ready", "지식 검색", health?.embeddings === "ready" ? "키워드·의미·하이브리드 검색" : "키워드 검색만 사용 중", <Search size={18} />)}{status(health?.telegram === "ready", "Telegram", health?.telegram === "ready" ? "웹훅과 보안값 준비됨" : "봇 토큰 등록 전", <MessageSquareText size={18} />)}</section><section className="monitor-grid"><article className="panel"><div className="panel-header"><div><h2>보안 경계</h2><p>현재 적용된 운영 원칙</p></div><ShieldCheck size={17} /></div><ul className="security-checks"><li><CheckCircle2 size={14} /> 비밀번호 로그인·세션 유지</li><li><CheckCircle2 size={14} /> 활성 구성원·관리자 역할 확인</li><li><CheckCircle2 size={14} /> RLS 기반 운영 기록 접근</li><li><CheckCircle2 size={14} /> Agent PAT 정본 읽기 전용</li><li><CheckCircle2 size={14} /> 수정 이력 자동 감사 로그</li><li><CheckCircle2 size={14} /> 회의 녹음 비공개 저장·서명 URL</li></ul></article><article className="panel"><div className="panel-header"><div><h2>외부 연결 준비</h2><p>자격 증명은 OS에 원문 저장하지 않음</p></div><Bot size={17} /></div><div className="connection-monitor">{connections.map((connection) => <div key={connection.id}><span className={`state-dot ${connection.status === "healthy" ? "" : "demo"}`} /><span><strong>{connection.title}</strong><small>{connection.description || "설정 위치와 담당자를 기록하세요."}</small></span><em>{connection.status}</em></div>)}{!connections.length ? <div className="quiet-state"><Bot size={21} /><strong>등록된 연결 없음</strong><span>설정 → 연결에서 시스템을 등록하세요.</span></div> : null}</div></article></section></>;
}
