"use client";

import { BarChart3, CheckCircle2, CircleAlert, Clipboard, Download, FileText, GitBranch, Target, TrendingUp } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { listAllRecords } from "@/lib/api-client";
import type { OsRecord } from "@/lib/record-types";
import { useSession } from "./session-provider";

function currentMonth() { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`; }
function monthOf(record: OsRecord) { const month = record.metadata?.periodMonth; return typeof month === "string" ? month : record.starts_at?.slice(0, 7) || record.due_date?.slice(0, 7) || record.created_at.slice(0, 7); }
function won(value: number) { return `${Math.round(value).toLocaleString("ko-KR")}원`; }

export function ReportsWorkspace() {
  const { accessToken, demo } = useSession();
  const [month, setMonth] = useState(currentMonth);
  const [records, setRecords] = useState<OsRecord[]>([]);
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);
  const load = useCallback(async () => { if (demo) return; try { const result = await listAllRecords(accessToken, "limit=200"); setRecords(result.records); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "보고서 데이터를 불러오지 못했습니다."); } }, [accessToken, demo]);
  useEffect(() => { load(); }, [load]);
  const monthly = records.filter((record) => monthOf(record) === month);
  const byType = (type: OsRecord["record_type"]) => monthly.filter((record) => record.record_type === type);
  const tasks = byType("task"), goals = [...byType("goal"), ...byType("kpi")], decisions = byType("decision"), meetings = byType("meeting"), contents = monthly.filter((record) => record.record_type.startsWith("content_")), revenue = byType("revenue");
  const taskDone = tasks.filter((record) => record.status === "done").length;
  const goalAttainment = goals.length ? Math.round(goals.reduce((sum, record) => sum + (record.metric_target ? Number(record.metric_current ?? 0) / Number(record.metric_target) * 100 : record.progress), 0) / goals.length) : 0;
  const revenueTotal = revenue.reduce((sum, record) => sum + Number(record.amount ?? record.metric_current ?? 0), 0);
  const report = useMemo(() => `# ${month.replace("-", "년 ")}월 브랜디액션 운영 보고서\n\n## 핵심 지표\n- 목표·KPI 평균 달성률: ${goalAttainment}%\n- 완료 업무: ${taskDone}/${tasks.length}\n- 매출 기록 합계: ${won(revenueTotal)}\n- 확정 의사결정: ${decisions.filter((record) => record.status === "decided").length}건\n- 완료 회의: ${meetings.filter((record) => record.status === "done").length}건\n- 발행 콘텐츠: ${contents.filter((record) => record.status === "published").length}건\n\n## 완료 업무\n${tasks.filter((record) => record.status === "done").map((record) => `- ${record.title}`).join("\n") || "- 없음"}\n\n## 막힌 업무\n${tasks.filter((record) => record.status === "blocked").map((record) => `- ${record.title}: ${record.description}`).join("\n") || "- 없음"}\n\n## 주요 결정\n${decisions.filter((record) => record.status === "decided").map((record) => `- ${record.title}`).join("\n") || "- 없음"}\n\n## 다음 달 이월\n${tasks.filter((record) => !["done", "cancelled"].includes(record.status)).map((record) => `- ${record.title} (${record.due_date || "기한 미정"})`).join("\n") || "- 없음"}\n`, [contents, decisions, goalAttainment, meetings, month, revenueTotal, taskDone, tasks]);
  const copy = async () => { await navigator.clipboard.writeText(report); setCopied(true); setTimeout(() => setCopied(false), 1800); };
  const download = () => { const url = URL.createObjectURL(new Blob([report], { type: "text/markdown;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = `brandyaction-report-${month}.md`; link.click(); URL.revokeObjectURL(url); };
  return <><header className="page-header"><div className="page-title-group"><span className="eyebrow">월간 보고서</span><h1>월간 운영 보고서</h1><p>목표·업무·결정·콘텐츠·매출 기록을 같은 기준 월로 자동 집계합니다.</p></div><div className="header-actions"><label className="month-control"><input type="month" value={month} onChange={(event) => setMonth(event.target.value)} /></label><button className="secondary-button" onClick={copy}><Clipboard size={15} /> {copied ? "복사됨" : "보고서 복사"}</button><button className="primary-button" onClick={download}><Download size={15} /> MD 내려받기</button></div></header>{error ? <div className="inline-alert danger"><CircleAlert size={16} /> {error}</div> : null}<section className="metric-grid compact-metrics"><div className="metric-card"><div className="metric-top"><span>KPI 달성률</span><span className="metric-icon"><Target size={16} /></span></div><div className="metric-value">{goalAttainment}%</div><div className="metric-caption">월 목표 평균</div></div><div className="metric-card"><div className="metric-top"><span>업무 완료율</span><span className="metric-icon"><CheckCircle2 size={16} /></span></div><div className="metric-value">{tasks.length ? Math.round(taskDone / tasks.length * 100) : 0}%</div><div className="metric-caption">{taskDone}/{tasks.length}개 완료</div></div><div className="metric-card"><div className="metric-top"><span>월 매출</span><span className="metric-icon"><TrendingUp size={16} /></span></div><div className="metric-value growth-money">{won(revenueTotal)}</div><div className="metric-caption">입력 기록 합계</div></div><div className="metric-card"><div className="metric-top"><span>발행 콘텐츠</span><span className="metric-icon"><BarChart3 size={16} /></span></div><div className="metric-value">{contents.filter((record) => record.status === "published").length}</div><div className="metric-caption">채널 합산</div></div></section><section className="report-layout"><article className="panel report-preview"><div className="panel-header"><div><h2>자동 생성 보고서</h2><p>현재 운영 기록 기준</p></div><FileText size={17} /></div><pre>{report}</pre></article><aside><article className="panel report-signals"><div className="panel-header"><div><h2>대표 확인 신호</h2><p>5초 안에 판단할 항목</p></div></div><div><span className="bad"><CircleAlert size={15} /></span><span><strong>막힌 업무</strong><small>{tasks.filter((record) => record.status === "blocked").length}건</small></span></div><div><span className="warn"><GitBranch size={15} /></span><span><strong>결정 대기</strong><small>{decisions.filter((record) => ["open", "review"].includes(record.status)).length}건</small></span></div><div><span className="good"><CheckCircle2 size={15} /></span><span><strong>완료 업무</strong><small>{taskDone}건</small></span></div></article></aside></section></>;
}
