// Stable OS routes, not the standalone prototype's hash-router addresses.
export const FULLSCREEN_ROUTES = {
  "/hr": "hr-employees",
  "/hr/employees": "hr-employees",
  "/hr/leave": "hr-leave",
  "/hr/leave-ledger": "hr-ledger",
  "/hr/documents": "hr-documents",
  "/hr/my-leave": "hr-self",
  "/finance/overview": "finance-overview",
  "/finance/sales": "finance-sales",
  "/finance/settlements": "finance-settlements",
  "/finance/bank": "finance-bank",
  "/finance/cards": "finance-cards",
  "/finance/recurring": "finance-recurring",
  "/finance/budget": "finance-budget",
  "/home": "home",
  "/content/topics": "topics",
  "/content/scripts": "scripts",
  "/content/packages": "packages",
  "/content/shorts": "shorts",
  "/content/publishing": "publish",
  "/content/review": "publish",
  "/content/automation": "derive",
  "/content/calendar": "calendar",
  "/content/youtube": "youtube",
  "/content/performance": "performance",
  "/content/comments": "comments",
  "/automation/dashboard": "automation-dashboard",
  "/automation/review": "automation-review",
  "/automation/requests": "automation-requests",
  "/automation/library": "automation-library",
  "/automation/calendar": "automation-calendar",
  "/automation/performance": "automation-performance",
  "/automation/templates": "automation-templates",
  "/automation/settings": "automation-settings",
  "/knowledge": "documents",
  "/knowledge/graph": "links",
  "/knowledge/search": "search",
  "/knowledge/review": "review",
  "/organization/meetings": "meetings",
  "/home/decisions": "decisions",
  "/organization/tasks": "tasks",
  "/organization/schedule": "schedule",
  "/organization/leave": "leave",
  "/organization/members": "members",
  "/knowledge/development": "requests",
  "/organization/agents": "ai",
  "/settings/connections": "settings",
  "/settings/monitoring": "monitoring",
  "/settings/channels": "channels",
  "/settings/access": "access",
  "/settings/audit": "audit",
  "/settings/company": "company",
  "/settings/account": "account",
} as const;

export function fullscreenScreen(path: string, tab?: string | null) {
  if (path.startsWith("/hr/employees/")) return "hr-person";
  if (path === "/knowledge" && tab === "canon") return "canon";
  if (path === "/knowledge/development" && (tab === "updates" || tab === "history")) return "updates";
  if (path === "/organization/schedule" && tab === "leave") return "leave";
  return FULLSCREEN_ROUTES[path as keyof typeof FULLSCREEN_ROUTES];
}
