export interface PageGuideDefinition { steps: readonly [string,string,string]; next: string }
// Text is the final handoff's section 6; menu aliases resolve before this lookup.
export const PAGE_GUIDES: Record<string,PageGuideDefinition> = {
  "/finance/overview": {steps:["기간과 사업을 골라 매출·입금·순수익을 비교합니다","확인이 필요한 항목을 눌러 해당 메뉴로 이동합니다","현재는 모의 데이터이며 실제 거래·발송은 실행하지 않습니다"],next:"/finance/sales"},
  "/finance/sales": {steps:["토스 결제와 외부 매출을 나누어 확인합니다","검색·필터로 주문을 찾고 상세에서 모의 환불 요청을 검토합니다","외부 매출을 추가하면 같은 기간 합계에 반영됩니다"],next:"/finance/settlements"},
  "/finance/settlements": {steps:["지급일별 또는 거래별 정산을 고릅니다","미확인·금액 차이 항목의 상세를 확인합니다","확인 사유를 기록하고 연결된 통장 입금을 봅니다"],next:"/finance/bank"},
  "/finance/bank": {steps:["통장을 고르고 CSV·XLSX 내역을 로컬에서 가져옵니다","중복·오류를 확인한 뒤 거래를 분류합니다","외부 매출·통장 간 이체는 후보를 확인해 연결합니다"],next:"/finance/cards"},
  "/finance/cards": {steps:["카드별 CSV·XLSX를 가져와 열과 미리보기를 확인합니다","미분류·증빙 필요 내역에 사업·계정과목·사용 목적을 입력합니다","규칙을 관리하고 필요한 내역을 CSV로 내보냅니다"],next:"/finance/recurring"},
  "/finance/recurring": {steps:["여러 달 반복된 카드지출에서 정기 결제 후보를 확인합니다","서비스별 담당과 유지·검토·해지 상태를 정합니다","해지 상태는 모의 기록이며 실제 구독을 해지하지 않습니다"],next:"/finance/budget"},
  "/finance/budget": {steps:["월별 고정비·변동비·인건비 예산을 확인합니다","자동 합산 항목과 직접 입력할 실적을 구분합니다","누락·초과를 검토하고 개요와 같은 월 순수익을 확인합니다"],next:"/finance/overview"},
  "/home": {steps:["위에서부터 기한이 빠른 일을 처리합니다","‘검토·승인’ 탭에서 내 검토 차례를 확인합니다","막힌 일은 링크를 눌러 해결 화면으로 갑니다"],next:"/content/topics"},
  "/content/topics": {steps:["매일 보는 채널을 모읍니다 — 비어 있으면 채널 탐색 사전에서 시작","‘탐색’에서 근거 영상을 연결하고 준비도 네 칸을 채웁니다","‘틈새’에서 소구점을 선택해 승인 요청한 뒤 기획으로 넘깁니다"],next:"/content/scripts"},
  "/content/scripts": {steps:["위에서 작업 중인 영상을 고르면 그 폴더가 열립니다","단계 칩으로 지금 단계의 문서만 봅니다","다듬기가 끝나면 문서를 검토 요청합니다"],next:"/content/packages"},
  "/content/packages": {steps:["‘검색’에서 시장 썸네일을 근거로 모읍니다","제목 · 썸네일 후보를 뽑습니다","채택한 안을 저장함에 넣습니다"],next:"/content/shorts"},
  "/content/shorts": {steps:["원본 영상과 스타일 템플릿을 정합니다","‘클립’에서 쓸 구간을 고릅니다","승인한 구간을 제작으로 넘깁니다"],next:"/content/publishing"},
  "/content/publishing": {steps:["유튜브 관리에서 준비한 키트를 확인합니다","최종 영상을 검수한 뒤 발행 조건을 승인합니다","승인된 조건으로 YouTube에 영상을 업로드합니다"],next:"/content/performance"},
  "/content/youtube": {steps:["영상을 고릅니다","발행 키트를 만들고 문안을 검수합니다","완료한 키트를 발행·업로드로 넘깁니다"],next:"/content/publishing"},
  "/content/comments": {steps:["‘답할 것’에서 질문부터 봅니다","초안을 받아 고친 뒤 답글을 보냅니다","좋은 질문은 ① 주제·기획으로 보냅니다"],next:"/content/performance"},
  "/automation/dashboard": {steps:["검토·요청·댓글 수를 먼저 봅니다","내 차례 항목을 눌러 처리 화면으로 이동합니다","프로젝트별 진행과 막힘을 확인합니다"],next:"/automation/review"},
  "/automation/review": {steps:["검토 대기 문안을 고릅니다","채널·파일·문안을 확인하고 승인합니다","승인된 항목만 예약하거나 직접 게시 완료로 기록합니다"],next:"/automation/calendar"},
  "/automation/requests": {steps:["대기 중인 Claude 요청을 확인합니다","요청 방식과 실패 사유를 봅니다","결과가 생기면 연결된 콘텐츠를 엽니다"],next:"/automation/library"},
  "/automation/library": {steps:["검색과 종류 필터로 결과물을 찾습니다","연결된 프로젝트와 현재 상태를 확인합니다","원본 작업 화면에서 이어서 편집합니다"],next:"/automation/templates"},
  "/automation/calendar": {steps:["주·월 보기를 고릅니다","예약 항목을 날짜별로 확인합니다","실패·수동 게시 항목은 오른쪽에서 처리합니다"],next:"/automation/performance"},
  "/automation/performance": {steps:["플랫폼과 경과일을 맞춰 비교합니다","누락 값과 실제 0을 구분합니다","표본이 충분할 때만 다음 가설을 정합니다"],next:"/automation/dashboard"},
  "/automation/templates": {steps:["카드뉴스 시안을 만들거나 고릅니다","색·글꼴·글자 수를 조정합니다","미리보기를 확인하고 저장합니다"],next:"/automation/review"},
  "/automation/settings": {steps:["기본 요청 방식을 선택합니다","검토·발행 안전 기준을 확인합니다","관리자가 저장한 설정을 모든 자동화 화면에서 사용합니다"],next:"/automation/dashboard"},
  "/content/performance": {steps:["플랫폼 탭을 고릅니다","같은 경과일(D+7 등)끼리 비교합니다","n<5면 결론을 미룹니다"],next:"/content/topics"},
  "/knowledge": {steps:["폴더에서 문서를 엽니다","정본을 고치면 변경 제안으로 저장되어 승인 전 원문은 그대로입니다","‘연결’ 탭에서 깨진 링크를 골라 수정하고 문서 담당을 확인합니다"],next:"/knowledge/review"},
  "/knowledge/vault": {steps:["내 문서 또는 소유자를 선택해 원본 폴더 트리를 엽니다","기존 경로에 문서를 저장하고 고유 ID 연결로 이동합니다","02_Wiki에서 회사 기준으로 쓸 문서만 선정해 검토를 요청합니다"],next:"/knowledge/review"},
  "/knowledge/notes": {steps:["오늘 노트나 인박스에 생각을 기록합니다","카테고리와 상태로 내 노트를 정리합니다","팀에 필요한 내용만 공유합니다"],next:"/knowledge/docs"},
  "/knowledge/meetings": {steps:["회의와 참석자를 정하고 안건을 적습니다","회의 중 메모에서 결정과 할 일을 추출합니다","모든 항목을 검수한 뒤 확정합니다"],next:"/knowledge/decisions"},
  "/knowledge/decisions": {steps:["확정된 결정을 찾아봅니다","원래 회의와 확인 시각을 확인합니다","확정 대기는 회의에서 검수합니다"],next:"/knowledge/meetings"},
  "/knowledge/docs": {steps:["카테고리별 팀 문서를 확인합니다","표·보드·갤러리에서 상태와 날짜를 정리합니다","기준이 된 문서는 정본 후보로 요청합니다"],next:"/knowledge/canon"},
  "/knowledge/canon": {steps:["승인된 기준과 검토 기한을 확인합니다","담당자가 기준을 유지하거나 변경 제안을 작성합니다","다른 승인자의 검토를 거쳐 새 버전을 반영합니다"],next:"/knowledge/review"},
  "/knowledge/graph": {steps:["문서와 연결을 공간별로 확인합니다","끊어진 연결과 연결 없는 문서를 찾습니다","권한 있는 원문에서 연결을 수정합니다"],next:"/knowledge/docs"},
  "/knowledge/templates": {steps:["회사 또는 내 템플릿을 고릅니다","필요한 기록 틀을 편집합니다","새 문서를 만들 공간은 별도로 선택합니다"],next:"/knowledge/notes"},
  "/knowledge/trash": {steps:["삭제된 문서의 원래 공간을 확인합니다","문서를 복원하거나 정본 재검토를 요청합니다","보존 대상은 영구 삭제할 수 없습니다"],next:"/knowledge"},
  "/knowledge/search": {steps:["찾을 말을 넣습니다","결과에서 정본 배지가 있는 문서를 먼저 봅니다","없으면 새 문서를 만듭니다"],next:"/knowledge"},
  "/knowledge/review": {steps:["문서 검토 또는 정본 변경 제안을 선택합니다","줄 단위 변경과 미리보기·댓글을 확인합니다","작성자와 다른 승인자 또는 위임자가 승인합니다"],next:"/knowledge"},
  "/organization/meetings": {steps:["회의 녹음이나 메모를 올립니다","뽑힌 결정 · 업무를 검수합니다","업무는 담당 · 기한을 정해 확정합니다"],next:"/organization/tasks"},
  "/organization/tasks": {steps:["‘분류 대기’부터 담당 · 기한을 정합니다","내 업무를 진행 상태로 옮깁니다","끝나면 완료로 옮깁니다"],next:"/home"},
  "/organization/schedule": {steps:["이번 주 회의 · 마감을 확인합니다","휴가를 신청합니다","승인 대기를 처리합니다"],next:"/home"},
  "/organization/members": {steps:["구성원과 역할을 확인합니다","새 직원 계정을 만듭니다(관리자)","관리자는 공용 계정을 표시해 AI 키 경고를 켭니다"],next:"/settings/access"},
  "/knowledge/development": {steps:["불편한 점을 요청으로 남깁니다","상태(접수 · 수정 중 · 검수 요청 · 해결)를 확인합니다","검수 요청이 오면 확인합니다"],next:"/knowledge/development?tab=updates"},
  "/knowledge/development?tab=updates": {steps:["최근 배포를 확인합니다","바뀐 화면을 직접 열어 봅니다","문제가 있으면 수정 요청을 남깁니다"],next:"/knowledge/development"},
  "/organization/agents": {steps:["대기 · 처리 중 작업을 확인합니다","실패한 작업의 사유를 봅니다","필요하면 다시 요청합니다"],next:"/home"},
  "/settings/connections": {steps:["회사 앱 연결이 ‘연결됨’인지 봅니다","사람별 채널 현황과 테스터 요청을 확인합니다","‘운영 점검’에서 막힌 작업을 확인합니다"],next:"/settings/audit"},
  "/settings/access": {steps:["역할과 AI 키의 단계·만료일을 확인합니다","공용 계정 키는 개인 계정 재발급 요청 알림을 보냅니다","새 키 발급과 기존 키 폐기는 관리자가 별도로 진행합니다"],next:"/settings/audit"},
  "/settings/audit": {steps:["기간을 고르면 서버에서 그 기간의 기록을 찾습니다","연속 수정을 펼쳐 변경 전·후 차이를 봅니다","권한이 있는 기록은 사유를 적고 이전 내용으로 새 버전을 만듭니다"],next:"/settings/connections"},
  "/settings/company": {steps:["승인자와 기간 위임을 확인합니다","브랜드 · 표시 이름을 확인합니다","텔레그램 승인 대기를 처리합니다"],next:"/settings/connections"},
  "/settings/account": {steps:["내 YouTube · 인스타 · Threads를 하나씩 연결합니다","같이 쓸 계정은 ‘팀 공유’를 켭니다 — 켜면 직원 누구나 게시 · 답글","‘만료’가 뜨면 ‘다시 연결’ — 내 할 일 ‘막힌 일’에도 올라옵니다"],next:"/content/publishing"},
};
export const guideClosedKey = (path:string) => `brandy-os-guide-closed:${path}`;
