begin;

-- Existing core contract in the brandyaction OS project:
-- os_profiles, os_documents, os_document_versions, os_document_chunks,
-- os_document_events, os_embedding_jobs and os_search_knowledge().
-- This migration adds the external access and observability layer without
-- deleting or altering the existing ERP tables in the same Supabase project.

do $$
begin
  if to_regclass('public.os_documents') is null
     or to_regclass('public.os_profiles') is null
     or to_regprocedure('public.os_search_knowledge(text,vector,integer,os_doc_status[],text,text,double precision)') is null then
    raise exception 'OS_CORE_SCHEMA_REQUIRED';
  end if;
end;
$$;

create table if not exists public.os_agent_keys (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 1 and 80),
  key_hash text not null unique check (key_hash ~ '^[a-f0-9]{64}$'),
  key_prefix text not null,
  scopes text[] not null default array['knowledge:search']::text[],
  allowed_statuses public.os_doc_status[] not null default array['canonical']::public.os_doc_status[],
  team text not null default '',
  brand text,
  active boolean not null default true,
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  last_used_at timestamptz,
  expires_at timestamptz,
  revoked_at timestamptz,
  check (scopes <@ array['knowledge:search']::text[])
);

create index if not exists os_agent_keys_active_idx
  on public.os_agent_keys (active, expires_at) where active;

create table if not exists public.os_search_logs (
  id bigint generated by default as identity primary key,
  actor_type text not null check (actor_type in ('user', 'agent')),
  actor_id text not null,
  query_length integer not null check (query_length between 0 and 1000),
  mode text not null check (mode in ('hybrid', 'keyword', 'semantic')),
  result_count integer not null default 0 check (result_count >= 0),
  took_ms integer not null default 0 check (took_ms >= 0),
  degraded boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists os_search_logs_created_idx on public.os_search_logs (created_at desc);
create index if not exists os_search_logs_actor_idx on public.os_search_logs (actor_type, actor_id, created_at desc);

create table if not exists public.os_channel_turns (
  id bigint generated by default as identity primary key,
  channel text not null check (channel in ('telegram', 'os_chat', 'mcp')),
  external_user_id text not null,
  external_chat_id text,
  question text not null check (char_length(question) between 1 and 4000),
  answer text not null check (char_length(answer) between 1 and 12000),
  source_document_ids uuid[] not null default '{}',
  saved_document_id uuid references public.os_documents(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists os_channel_turns_user_idx
  on public.os_channel_turns (channel, external_user_id, created_at desc);

alter table public.os_agent_keys enable row level security;
alter table public.os_search_logs enable row level security;
alter table public.os_channel_turns enable row level security;

drop policy if exists os_agent_keys_admin_select on public.os_agent_keys;
create policy os_agent_keys_admin_select on public.os_agent_keys
  for select to authenticated using (public.os_is_admin());

drop policy if exists os_search_logs_admin_select on public.os_search_logs;
create policy os_search_logs_admin_select on public.os_search_logs
  for select to authenticated using (public.os_is_admin() or actor_id = auth.uid()::text);

drop policy if exists os_channel_turns_admin_select on public.os_channel_turns;
create policy os_channel_turns_admin_select on public.os_channel_turns
  for select to authenticated using (public.os_is_admin());

revoke all on public.os_agent_keys, public.os_search_logs, public.os_channel_turns from anon;
revoke insert, update, delete on public.os_agent_keys, public.os_search_logs, public.os_channel_turns from authenticated;
grant select on public.os_agent_keys, public.os_search_logs, public.os_channel_turns to authenticated;
grant all on public.os_agent_keys, public.os_search_logs, public.os_channel_turns to service_role;
grant usage, select on sequence public.os_search_logs_id_seq, public.os_channel_turns_id_seq to service_role;

commit;
