begin;

-- A stable organization id is part of the external agent contract. Brandy OS
-- is currently single-tenant, but the id prevents a PAT issued for one OS from
-- being replayed against a different organization if multi-tenancy is added.
create table if not exists public.os_organizations (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9][a-z0-9-]{1,62}$'),
  name text not null check (char_length(name) between 1 and 120),
  created_at timestamptz not null default now()
);

insert into public.os_organizations (slug, name)
values ('brandyaction', '브랜디액션')
on conflict (slug) do update set name = excluded.name;

alter table public.os_organizations enable row level security;

drop policy if exists os_organizations_member_select on public.os_organizations;
create policy os_organizations_member_select on public.os_organizations
  for select to authenticated using (public.os_is_active_member());

alter table public.os_agent_keys
  add column if not exists organization_id uuid references public.os_organizations(id) on delete restrict,
  add column if not exists owner_user_id uuid references auth.users(id) on delete restrict;

update public.os_agent_keys
set organization_id = (select id from public.os_organizations where slug = 'brandyaction')
where organization_id is null;

update public.os_agent_keys
set owner_user_id = created_by
where owner_user_id is null;

alter table public.os_agent_keys
  alter column organization_id set not null,
  alter column owner_user_id set not null,
  alter column scopes set default array['knowledge.read']::text[];

alter table public.os_agent_keys drop constraint if exists os_agent_keys_scopes_check;

update public.os_agent_keys
set scopes = array['knowledge.read']::text[]
where scopes = array['knowledge:search']::text[];

alter table public.os_agent_keys
  add constraint os_agent_keys_scopes_check
  check (
    cardinality(scopes) between 1 and 2
    and scopes <@ array['knowledge.read', 'knowledge.write']::text[]
  );

alter table public.os_document_versions
  add column if not exists agent_key_id uuid references public.os_agent_keys(id) on delete set null;

create table if not exists public.os_agent_audit_logs (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.os_organizations(id) on delete restrict,
  agent_key_id uuid not null references public.os_agent_keys(id) on delete restrict,
  owner_user_id uuid not null references auth.users(id) on delete restrict,
  action text not null check (action in ('knowledge.create', 'knowledge.update', 'knowledge.delete')),
  document_id uuid references public.os_documents(id) on delete set null,
  title_snapshot text not null default '',
  changed_fields text[] not null default '{}',
  reason text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists os_agent_audit_logs_agent_created_idx
  on public.os_agent_audit_logs (agent_key_id, created_at desc);
create index if not exists os_agent_audit_logs_document_created_idx
  on public.os_agent_audit_logs (document_id, created_at desc);

alter table public.os_agent_audit_logs enable row level security;

drop policy if exists os_agent_audit_logs_admin_select on public.os_agent_audit_logs;
create policy os_agent_audit_logs_admin_select on public.os_agent_audit_logs
  for select to authenticated using (public.os_is_admin());

create or replace function public.os_assert_agent_write_access(
  p_agent_key_id uuid,
  p_organization_id uuid,
  p_action text
) returns public.os_agent_keys
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  k public.os_agent_keys;
  v_minute_limit integer := case when p_action = 'knowledge.delete' then 5 else 20 end;
  v_day_limit integer := case when p_action = 'knowledge.delete' then 30 else 200 end;
  v_minute_count integer;
  v_day_count integer;
begin
  select * into k
  from public.os_agent_keys
  where id = p_agent_key_id
    and organization_id = p_organization_id
    and active
    and 'knowledge.write' = any(scopes)
    and (expires_at is null or expires_at > now())
  for update;

  if not found then
    raise exception 'OS_AGENT_WRITE_DENIED' using errcode = 'P0001';
  end if;

  select count(*) into v_minute_count
  from public.os_agent_audit_logs
  where agent_key_id = p_agent_key_id
    and action = p_action
    and created_at >= now() - interval '1 minute';

  select count(*) into v_day_count
  from public.os_agent_audit_logs
  where agent_key_id = p_agent_key_id
    and action = p_action
    and created_at >= now() - interval '24 hours';

  if v_minute_count >= v_minute_limit or v_day_count >= v_day_limit then
    raise exception 'OS_AGENT_RATE_LIMITED' using errcode = 'P0001';
  end if;

  return k;
end;
$$;

create or replace function public.os_agent_create_document(
  p_agent_key_id uuid,
  p_organization_id uuid,
  p_title text,
  p_content_md text,
  p_folder text default 'AI 저장/검토 대기',
  p_brand text default '',
  p_team text default '',
  p_tags text[] default '{}',
  p_reason text default ''
) returns public.os_documents
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  k public.os_agent_keys;
  d public.os_documents;
begin
  k := public.os_assert_agent_write_access(p_agent_key_id, p_organization_id, 'knowledge.create');
  if char_length(trim(p_title)) < 1 or char_length(p_content_md) < 1 then
    raise exception 'OS_AGENT_DOCUMENT_INVALID' using errcode = 'P0001';
  end if;

  perform set_config('os.agent_key_id', p_agent_key_id::text, true);
  insert into public.os_documents (
    title, content_md, folder, brand, team, tags, source, status, owner_id, created_by
  ) values (
    trim(p_title), p_content_md, coalesce(p_folder, 'AI 저장/검토 대기'),
    coalesce(p_brand, k.brand, ''), coalesce(nullif(p_team, ''), k.team, ''),
    coalesce(p_tags, '{}'), 'mcp', 'draft', k.owner_user_id, k.owner_user_id
  ) returning * into d;

  update public.os_document_versions
  set agent_key_id = p_agent_key_id
  where document_id = d.id and version_no = d.current_version;

  update public.os_document_events
  set actor_id = k.owner_user_id, note = concat('MCP 에이전트 ', k.name, ': 생성')
  where document_id = d.id and actor_id is null and note = 'created';

  insert into public.os_agent_audit_logs (
    organization_id, agent_key_id, owner_user_id, action, document_id,
    title_snapshot, changed_fields, reason
  ) values (
    p_organization_id, p_agent_key_id, k.owner_user_id, 'knowledge.create', d.id,
    d.title, array['title', 'content_md', 'folder', 'tags'], coalesce(p_reason, '')
  );
  return d;
end;
$$;

create or replace function public.os_agent_update_document(
  p_agent_key_id uuid,
  p_organization_id uuid,
  p_document_id uuid,
  p_expected_version integer,
  p_title text,
  p_content_md text,
  p_folder text,
  p_brand text,
  p_team text,
  p_tags text[],
  p_changed_fields text[],
  p_reason text default ''
) returns public.os_documents
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  k public.os_agent_keys;
  d public.os_documents;
begin
  k := public.os_assert_agent_write_access(p_agent_key_id, p_organization_id, 'knowledge.update');
  select * into d from public.os_documents where id = p_document_id for update;
  if not found then raise exception 'OS_DOC_NOT_FOUND' using errcode = 'P0002'; end if;
  if d.status = 'archived' then raise exception 'OS_AGENT_ARCHIVED_READ_ONLY' using errcode = 'P0001'; end if;
  if d.owner_id <> k.owner_user_id and d.status <> 'canonical' then
    raise exception 'OS_AGENT_DOCUMENT_DENIED' using errcode = 'P0001';
  end if;
  if d.current_version <> p_expected_version then
    raise exception 'OS_VERSION_CONFLICT:%', d.current_version using errcode = 'P0001';
  end if;

  perform set_config('os.version_reason', coalesce(nullif(p_reason, ''), 'MCP 에이전트 수정'), true);
  perform set_config('os.agent_key_id', p_agent_key_id::text, true);
  update public.os_documents
  set title = p_title, content_md = p_content_md, folder = p_folder,
      brand = p_brand, team = p_team, tags = coalesce(p_tags, '{}')
  where id = p_document_id
  returning * into d;

  update public.os_document_versions
  set agent_key_id = p_agent_key_id
  where document_id = d.id and version_no = d.current_version;

  insert into public.os_agent_audit_logs (
    organization_id, agent_key_id, owner_user_id, action, document_id,
    title_snapshot, changed_fields, reason
  ) values (
    p_organization_id, p_agent_key_id, k.owner_user_id, 'knowledge.update', d.id,
    d.title, coalesce(p_changed_fields, '{}'), coalesce(p_reason, '')
  );
  return d;
end;
$$;

create or replace function public.os_agent_archive_document(
  p_agent_key_id uuid,
  p_organization_id uuid,
  p_document_id uuid,
  p_reason text default ''
) returns public.os_documents
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  k public.os_agent_keys;
  d public.os_documents;
  v_from public.os_doc_status;
begin
  k := public.os_assert_agent_write_access(p_agent_key_id, p_organization_id, 'knowledge.delete');
  select * into d from public.os_documents where id = p_document_id for update;
  if not found then raise exception 'OS_DOC_NOT_FOUND' using errcode = 'P0002'; end if;
  if d.owner_id <> k.owner_user_id and d.status <> 'canonical' then
    raise exception 'OS_AGENT_DOCUMENT_DENIED' using errcode = 'P0001';
  end if;
  if d.status = 'archived' then return d; end if;

  v_from := d.status;
  perform set_config('os.status_change_ok', '1', true);
  perform set_config('os.agent_key_id', p_agent_key_id::text, true);
  update public.os_documents set status = 'archived' where id = p_document_id returning * into d;
  perform set_config('os.status_change_ok', '', true);

  insert into public.os_document_events (document_id, from_status, to_status, actor_id, note)
  values (
    p_document_id, v_from, 'archived', k.owner_user_id,
    concat('MCP 에이전트 ', k.name, ': ', coalesce(p_reason, '휴지통 이동'))
  );
  insert into public.os_agent_audit_logs (
    organization_id, agent_key_id, owner_user_id, action, document_id,
    title_snapshot, changed_fields, reason
  ) values (
    p_organization_id, p_agent_key_id, k.owner_user_id, 'knowledge.delete', d.id,
    d.title, array['status'], coalesce(p_reason, '휴지통 이동')
  );
  return d;
end;
$$;

revoke all on function public.os_assert_agent_write_access(uuid, uuid, text) from public, anon, authenticated;
revoke all on function public.os_agent_create_document(uuid, uuid, text, text, text, text, text, text[], text) from public, anon, authenticated;
revoke all on function public.os_agent_update_document(uuid, uuid, uuid, integer, text, text, text, text, text, text[], text[], text) from public, anon, authenticated;
revoke all on function public.os_agent_archive_document(uuid, uuid, uuid, text) from public, anon, authenticated;

grant execute on function public.os_assert_agent_write_access(uuid, uuid, text) to service_role;
grant execute on function public.os_agent_create_document(uuid, uuid, text, text, text, text, text, text[], text) to service_role;
grant execute on function public.os_agent_update_document(uuid, uuid, uuid, integer, text, text, text, text, text, text[], text[], text) to service_role;
grant execute on function public.os_agent_archive_document(uuid, uuid, uuid, text) to service_role;

commit;
