begin;

-- Shared operating layer for projects, work, decisions, meetings, content and growth.
-- Knowledge tables remain the source of truth for documents; this layer connects
-- execution records to the same people, teams and brands without deleting data.

create table if not exists public.os_records (
  id uuid primary key default gen_random_uuid(),
  record_type text not null check (record_type in (
    'project', 'task', 'goal', 'kpi', 'decision', 'meeting', 'ai_job',
    'content_topic', 'content_script', 'content_package', 'content_short',
    'content_publish', 'content_metric', 'skill', 'knowledge_link',
    'revenue', 'funnel', 'crm_action', 'customer', 'brand',
    'connection', 'access_rule', 'company_setting', 'channel'
  )),
  title text not null check (char_length(title) between 1 and 240),
  description text not null default '' check (char_length(description) <= 20000),
  status text not null default 'backlog' check (char_length(status) between 1 and 40),
  priority text not null default 'normal' check (priority in ('low', 'normal', 'high', 'urgent')),
  stage text not null default '' check (char_length(stage) <= 80),
  brand text not null default '' check (char_length(brand) <= 120),
  team text not null default '' check (char_length(team) <= 120),
  owner_id uuid references auth.users(id) on delete set null,
  assignee_id uuid references auth.users(id) on delete set null,
  parent_id uuid references public.os_records(id) on delete restrict,
  due_date date,
  starts_at timestamptz,
  ends_at timestamptz,
  progress integer not null default 0 check (progress between 0 and 100),
  metric_target numeric,
  metric_current numeric,
  metric_unit text not null default '' check (char_length(metric_unit) <= 30),
  amount numeric,
  currency text not null default 'KRW' check (currency ~ '^[A-Z]{3}$'),
  source_url text check (source_url is null or char_length(source_url) <= 2000),
  tags text[] not null default '{}',
  metadata jsonb not null default '{}'::jsonb,
  version integer not null default 1 check (version > 0),
  created_by uuid not null references auth.users(id) on delete restrict,
  updated_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  check (parent_id is null or parent_id <> id),
  check (cardinality(tags) <= 30),
  check (ends_at is null or starts_at is null or ends_at >= starts_at)
);

create index if not exists os_records_type_status_idx
  on public.os_records (record_type, status, updated_at desc) where archived_at is null;
create index if not exists os_records_assignee_idx
  on public.os_records (assignee_id, due_date) where archived_at is null;
create index if not exists os_records_parent_idx
  on public.os_records (parent_id, record_type) where archived_at is null;
create index if not exists os_records_brand_team_idx
  on public.os_records (brand, team, updated_at desc) where archived_at is null;
create index if not exists os_records_tags_idx on public.os_records using gin (tags);

create table if not exists public.os_record_events (
  id bigint generated by default as identity primary key,
  record_id uuid not null references public.os_records(id) on delete restrict,
  actor_id uuid references auth.users(id) on delete set null,
  event_type text not null check (char_length(event_type) between 1 and 80),
  from_status text,
  to_status text,
  changed_fields text[] not null default '{}',
  note text not null default '' check (char_length(note) <= 4000),
  snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists os_record_events_record_idx
  on public.os_record_events (record_id, created_at desc);
create index if not exists os_record_events_actor_idx
  on public.os_record_events (actor_id, created_at desc);

create or replace function public.os_is_active_member()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.os_profiles p
    where p.id = auth.uid() and p.is_active = true
  );
$$;

create or replace function public.os_records_before_write()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if tg_op = 'INSERT' then
    new.created_by := coalesce(new.created_by, auth.uid());
    new.updated_by := coalesce(new.updated_by, auth.uid());
    new.owner_id := coalesce(new.owner_id, auth.uid());
    new.version := 1;
  else
    new.updated_by := coalesce(auth.uid(), new.updated_by);
    new.updated_at := now();
    new.version := old.version + 1;
  end if;
  return new;
end;
$$;

drop trigger if exists os_records_before_write_trigger on public.os_records;
create trigger os_records_before_write_trigger
before insert or update on public.os_records
for each row execute function public.os_records_before_write();

create or replace function public.os_records_after_write()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_changed text[] := '{}';
begin
  if tg_op = 'INSERT' then
    insert into public.os_record_events (
      record_id, actor_id, event_type, to_status, snapshot
    ) values (
      new.id, new.created_by, 'created', new.status, to_jsonb(new)
    );
  else
    if old.title is distinct from new.title then v_changed := array_append(v_changed, 'title'); end if;
    if old.description is distinct from new.description then v_changed := array_append(v_changed, 'description'); end if;
    if old.status is distinct from new.status then v_changed := array_append(v_changed, 'status'); end if;
    if old.assignee_id is distinct from new.assignee_id then v_changed := array_append(v_changed, 'assignee_id'); end if;
    if old.due_date is distinct from new.due_date then v_changed := array_append(v_changed, 'due_date'); end if;
    if old.progress is distinct from new.progress then v_changed := array_append(v_changed, 'progress'); end if;
    if old.metric_current is distinct from new.metric_current then v_changed := array_append(v_changed, 'metric_current'); end if;
    if old.archived_at is distinct from new.archived_at then v_changed := array_append(v_changed, 'archived_at'); end if;
    insert into public.os_record_events (
      record_id, actor_id, event_type, from_status, to_status, changed_fields, snapshot
    ) values (
      new.id, new.updated_by,
      case when new.archived_at is not null and old.archived_at is null then 'archived' else 'updated' end,
      old.status, new.status, v_changed, to_jsonb(new)
    );
  end if;
  return new;
end;
$$;

drop trigger if exists os_records_after_write_trigger on public.os_records;
create trigger os_records_after_write_trigger
after insert or update on public.os_records
for each row execute function public.os_records_after_write();

alter table public.os_records enable row level security;
alter table public.os_record_events enable row level security;

drop policy if exists os_records_active_select on public.os_records;
create policy os_records_active_select on public.os_records
  for select to authenticated using (public.os_is_active_member());

drop policy if exists os_records_active_insert on public.os_records;
create policy os_records_active_insert on public.os_records
  for insert to authenticated with check (
    public.os_is_active_member() and created_by = auth.uid() and updated_by = auth.uid()
  );

drop policy if exists os_records_owner_update on public.os_records;
create policy os_records_owner_update on public.os_records
  for update to authenticated using (
    public.os_is_active_member()
    and (
      created_by = auth.uid() or owner_id = auth.uid() or assignee_id = auth.uid()
      or public.os_is_admin()
    )
  ) with check (public.os_is_active_member());

drop policy if exists os_record_events_active_select on public.os_record_events;
create policy os_record_events_active_select on public.os_record_events
  for select to authenticated using (public.os_is_active_member());

revoke all on public.os_records, public.os_record_events from anon;
grant select, insert, update on public.os_records to authenticated;
grant select on public.os_record_events to authenticated;
grant all on public.os_records, public.os_record_events to service_role;
grant usage, select on sequence public.os_record_events_id_seq to service_role, authenticated;

commit;
