import { constants } from "node:fs";
import { access, readFile, writeFile } from "node:fs/promises";

const templateUrl = new URL("../.env.example", import.meta.url);
const targetUrl = new URL("../.env.local", import.meta.url);

try {
  await access(targetUrl, constants.F_OK);
  console.log("[local-setup] .env.local already exists; no changes made");
  process.exit(0);
} catch (error) {
  if (error?.code !== "ENOENT") throw error;
}

const template = await readFile(templateUrl, "utf8");
const localEnvironment = template
  .replace(/^OS_ENVIRONMENT=.*$/m, "OS_ENVIRONMENT=local")
  .replace(/^NEXT_PUBLIC_DEMO_MODE=.*$/m, "NEXT_PUBLIC_DEMO_MODE=true");

await writeFile(
  targetUrl,
  `# Generated by npm run setup:local. Keep secrets out of Git.\n${localEnvironment}`,
  { encoding: "utf8", flag: "wx", mode: 0o600 },
);

console.log("[local-setup] created .env.local in safe demo mode");
