-- Employee account onboarding and password lifecycle.
-- The shared initial password is never stored in Postgres; it remains a server-only secret.

alter table public.os_profiles
  add column if not exists legal_name text not null default '',
  add column if not exists must_change_password boolean not null default false,
  add column if not exists password_changed_at timestamptz,
  add column if not exists password_reset_at timestamptz,
  add column if not exists password_reset_by uuid references auth.users(id) on delete set null;

create table if not exists public.os_security_audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  target_user_id uuid not null references auth.users(id) on delete cascade,
  action text not null check (action in ('account.created', 'password.changed', 'password.reset')),
  note text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists os_security_audit_actor_created_idx
  on public.os_security_audit_logs (actor_id, created_at desc);
create index if not exists os_security_audit_target_created_idx
  on public.os_security_audit_logs (target_user_id, created_at desc);

alter table public.os_security_audit_logs enable row level security;

drop policy if exists os_security_audit_admin_select on public.os_security_audit_logs;
create policy os_security_audit_admin_select on public.os_security_audit_logs
  for select to authenticated using (public.os_is_admin());

drop policy if exists os_security_audit_self_select on public.os_security_audit_logs;
create policy os_security_audit_self_select on public.os_security_audit_logs
  for select to authenticated using (target_user_id = auth.uid() or actor_id = auth.uid());

grant select on public.os_security_audit_logs to authenticated;
grant all on public.os_security_audit_logs to service_role;
grant usage, select on sequence public.os_security_audit_logs_id_seq to service_role;

