begin;

alter table public.os_channel_turns
  add column if not exists request_message_id bigint,
  add column if not exists response_message_id bigint,
  add column if not exists reply_to_message_id bigint,
  add column if not exists metadata jsonb not null default '{}'::jsonb;

alter table public.os_telegram_users
  add column if not exists profile_id uuid references public.os_profiles(id) on delete set null;

create unique index if not exists os_channel_turns_telegram_response_idx
  on public.os_channel_turns(channel, external_chat_id, response_message_id)
  where channel = 'telegram' and response_message_id is not null;
create unique index if not exists os_telegram_users_profile_idx
  on public.os_telegram_users(profile_id) where profile_id is not null;
create unique index if not exists os_records_telegram_action_turn_idx
  on public.os_records((metadata->>'telegramTurnId'))
  where archived_at is null and metadata->>'kind' = 'telegram_confirmed_action';
create unique index if not exists os_records_telegram_feedback_turn_idx
  on public.os_records((metadata->>'turnId'))
  where archived_at is null and metadata->>'kind' = 'telegram_answer_feedback';

create table if not exists public.os_telegram_chats (
  external_chat_id text primary key,
  chat_type text not null default 'private',
  title text not null default '',
  digest_enabled boolean not null default false,
  digest_hour_kst smallint not null default 9 check (digest_hour_kst between 0 and 23),
  enabled_by uuid references public.os_profiles(id) on delete set null,
  last_digest_fingerprint text not null default '',
  last_digest_sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.os_telegram_feedback (
  id bigint generated by default as identity primary key,
  turn_id bigint not null references public.os_channel_turns(id) on delete restrict,
  reporter_external_user_id text not null,
  kind text not null check (kind in ('ok','stale','wrong','canonical')),
  created_at timestamptz not null default now(),
  unique(turn_id, reporter_external_user_id)
);

alter table public.os_telegram_chats enable row level security;
alter table public.os_telegram_feedback enable row level security;
create policy os_telegram_chats_admin_select on public.os_telegram_chats for select to authenticated using (public.os_is_admin());
create policy os_telegram_chats_admin_update on public.os_telegram_chats for update to authenticated using (public.os_is_admin()) with check (public.os_is_admin());
create policy os_telegram_feedback_admin_select on public.os_telegram_feedback for select to authenticated using (public.os_is_admin());
grant select, update on public.os_telegram_chats to authenticated;
grant select on public.os_telegram_feedback to authenticated;
grant all on public.os_telegram_chats, public.os_telegram_feedback to service_role;
grant all on sequence public.os_telegram_feedback_id_seq to service_role;

commit;
